// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: covesa/ivdct/truck/vehicle/genericvehicle/genericvehicle.proto
// Protobuf C++ Version: 6.31.1

#include "covesa/ivdct/truck/vehicle/genericvehicle/genericvehicle.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace VEHICLE {
namespace GENERICVEHICLE {

inline constexpr Genericvehicle::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : angularvelocity_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Genericvehicle::Genericvehicle(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Genericvehicle_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GenericvehicleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GenericvehicleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GenericvehicleDefaultTypeInternal() {}
  union {
    Genericvehicle _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GenericvehicleDefaultTypeInternal _Genericvehicle_default_instance_;
}  // namespace GENERICVEHICLE
}  // namespace VEHICLE
}  // namespace TRUCK
}  // namespace IVDCT
}  // namespace COVESA
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto = nullptr;
const ::uint32_t
    TableStruct_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::COVESA::IVDCT::TRUCK::VEHICLE::GENERICVEHICLE::Genericvehicle, _impl_.angularvelocity_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::COVESA::IVDCT::TRUCK::VEHICLE::GENERICVEHICLE::Genericvehicle)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::COVESA::IVDCT::TRUCK::VEHICLE::GENERICVEHICLE::_Genericvehicle_default_instance_._instance,
};
const char descriptor_table_protodef_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n>covesa/ivdct/truck/vehicle/genericvehi"
    "cle/genericvehicle.proto\022)COVESA.IVDCT.T"
    "RUCK.VEHICLE.GENERICVEHICLE\032Ocovesa/ivdc"
    "t/truck/vehicle/genericvehicle/angularve"
    "locity/angularvelocity.proto\"u\n\016Genericv"
    "ehicle\022c\n\017angularvelocity\030\001 \003(\0132J.COVESA"
    ".IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.ANGU"
    "LARVELOCITY.Angularvelocityb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto_deps[1] = {
        &::descriptor_table_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fangularvelocity_2fangularvelocity_2eproto,
};
static ::absl::once_flag descriptor_table_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto = {
    false,
    false,
    315,
    descriptor_table_protodef_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto,
    "covesa/ivdct/truck/vehicle/genericvehicle/genericvehicle.proto",
    &descriptor_table_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto_once,
    descriptor_table_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto::offsets,
    file_level_enum_descriptors_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto,
    file_level_service_descriptors_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto,
};
namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace VEHICLE {
namespace GENERICVEHICLE {
// ===================================================================

class Genericvehicle::_Internal {
 public:
};

void Genericvehicle::clear_angularvelocity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angularvelocity_.Clear();
}
Genericvehicle::Genericvehicle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Genericvehicle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
}
PROTOBUF_NDEBUG_INLINE Genericvehicle::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::COVESA::IVDCT::TRUCK::VEHICLE::GENERICVEHICLE::Genericvehicle& from_msg)
      : angularvelocity_{visibility, arena, from.angularvelocity_},
        _cached_size_{0} {}

Genericvehicle::Genericvehicle(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Genericvehicle& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Genericvehicle_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Genericvehicle* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
}
PROTOBUF_NDEBUG_INLINE Genericvehicle::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : angularvelocity_{visibility, arena},
        _cached_size_{0} {}

inline void Genericvehicle::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Genericvehicle::~Genericvehicle() {
  // @@protoc_insertion_point(destructor:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
  SharedDtor(*this);
}
inline void Genericvehicle::SharedDtor(MessageLite& self) {
  Genericvehicle& this_ = static_cast<Genericvehicle&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Genericvehicle::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Genericvehicle(arena);
}
constexpr auto Genericvehicle::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Genericvehicle, _impl_.angularvelocity_) +
          decltype(Genericvehicle::_impl_.angularvelocity_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Genericvehicle), alignof(Genericvehicle), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Genericvehicle::PlacementNew_,
                                 sizeof(Genericvehicle),
                                 alignof(Genericvehicle));
  }
}
constexpr auto Genericvehicle::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Genericvehicle_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Genericvehicle::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Genericvehicle>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Genericvehicle::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Genericvehicle>(), &Genericvehicle::ByteSizeLong,
              &Genericvehicle::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Genericvehicle, _impl_._cached_size_),
          false,
      },
      &Genericvehicle::kDescriptorMethods,
      &descriptor_table_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Genericvehicle_class_data_ =
        Genericvehicle::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Genericvehicle::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Genericvehicle_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Genericvehicle_class_data_.tc_table);
  return Genericvehicle_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
Genericvehicle::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Genericvehicle_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::COVESA::IVDCT::TRUCK::VEHICLE::GENERICVEHICLE::Genericvehicle>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.ANGULARVELOCITY.Angularvelocity angularvelocity = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Genericvehicle, _impl_.angularvelocity_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.ANGULARVELOCITY.Angularvelocity angularvelocity = 1;
    {PROTOBUF_FIELD_OFFSET(Genericvehicle, _impl_.angularvelocity_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::COVESA::IVDCT::TRUCK::VEHICLE::GENERICVEHICLE::ANGULARVELOCITY::Angularvelocity>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Genericvehicle::Clear() {
// @@protoc_insertion_point(message_clear_start:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.angularvelocity_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Genericvehicle::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Genericvehicle& this_ = static_cast<const Genericvehicle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Genericvehicle::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Genericvehicle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.ANGULARVELOCITY.Angularvelocity angularvelocity = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_angularvelocity_size());
       i < n; i++) {
    const auto& repfield = this_._internal_angularvelocity().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Genericvehicle::ByteSizeLong(const MessageLite& base) {
  const Genericvehicle& this_ = static_cast<const Genericvehicle&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Genericvehicle::ByteSizeLong() const {
  const Genericvehicle& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.ANGULARVELOCITY.Angularvelocity angularvelocity = 1;
    {
      total_size += 1UL * this_._internal_angularvelocity_size();
      for (const auto& msg : this_._internal_angularvelocity()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Genericvehicle::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Genericvehicle*>(&to_msg);
  auto& from = static_cast<const Genericvehicle&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_angularvelocity()->MergeFrom(
      from._internal_angularvelocity());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Genericvehicle::CopyFrom(const Genericvehicle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:COVESA.IVDCT.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Genericvehicle::InternalSwap(Genericvehicle* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.angularvelocity_.InternalSwap(&other->_impl_.angularvelocity_);
}

::google::protobuf::Metadata Genericvehicle::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace GENERICVEHICLE
}  // namespace VEHICLE
}  // namespace TRUCK
}  // namespace IVDCT
}  // namespace COVESA
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_covesa_2fivdct_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
