// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: covesa/ads_lf/truck/vehicle/genericvehicle/genericvehicle.proto
// Protobuf C++ Version: 6.31.1

#ifndef covesa_2fads_5flf_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto_2epb_2eh
#define covesa_2fads_5flf_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "validate/validate.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_covesa_2fads_5flf_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_covesa_2fads_5flf_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_covesa_2fads_5flf_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto;
}  // extern "C"
namespace COVESA {
namespace ADS_LF {
namespace TRUCK {
namespace VEHICLE {
namespace GENERICVEHICLE {
class Genericvehicle;
struct GenericvehicleDefaultTypeInternal;
extern GenericvehicleDefaultTypeInternal _Genericvehicle_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Genericvehicle_class_data_;
}  // namespace GENERICVEHICLE
}  // namespace VEHICLE
}  // namespace TRUCK
}  // namespace ADS_LF
}  // namespace COVESA
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace COVESA {
namespace ADS_LF {
namespace TRUCK {
namespace VEHICLE {
namespace GENERICVEHICLE {

// ===================================================================


// -------------------------------------------------------------------

class Genericvehicle final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle) */ {
 public:
  inline Genericvehicle() : Genericvehicle(nullptr) {}
  ~Genericvehicle() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Genericvehicle* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Genericvehicle));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Genericvehicle(::google::protobuf::internal::ConstantInitialized);

  inline Genericvehicle(const Genericvehicle& from) : Genericvehicle(nullptr, from) {}
  inline Genericvehicle(Genericvehicle&& from) noexcept
      : Genericvehicle(nullptr, ::std::move(from)) {}
  inline Genericvehicle& operator=(const Genericvehicle& from) {
    CopyFrom(from);
    return *this;
  }
  inline Genericvehicle& operator=(Genericvehicle&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Genericvehicle& default_instance() {
    return *reinterpret_cast<const Genericvehicle*>(
        &_Genericvehicle_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Genericvehicle& a, Genericvehicle& b) { a.Swap(&b); }
  inline void Swap(Genericvehicle* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Genericvehicle* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Genericvehicle* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Genericvehicle>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Genericvehicle& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Genericvehicle& from) { Genericvehicle::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Genericvehicle* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle"; }

 protected:
  explicit Genericvehicle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Genericvehicle(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Genericvehicle& from);
  Genericvehicle(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Genericvehicle&& from) noexcept
      : Genericvehicle(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCurbweightFieldNumber = 1,
    kLengthFieldNumber = 2,
    kHeightFieldNumber = 3,
    kWidthFieldNumber = 4,
  };
  // optional uint32 curbweight = 1 [(.validate.rules) = {
  bool has_curbweight() const;
  void clear_curbweight() ;
  ::uint32_t curbweight() const;
  void set_curbweight(::uint32_t value);

  private:
  ::uint32_t _internal_curbweight() const;
  void _internal_set_curbweight(::uint32_t value);

  public:
  // optional uint32 length = 2 [(.validate.rules) = {
  bool has_length() const;
  void clear_length() ;
  ::uint32_t length() const;
  void set_length(::uint32_t value);

  private:
  ::uint32_t _internal_length() const;
  void _internal_set_length(::uint32_t value);

  public:
  // optional uint32 height = 3 [(.validate.rules) = {
  bool has_height() const;
  void clear_height() ;
  ::uint32_t height() const;
  void set_height(::uint32_t value);

  private:
  ::uint32_t _internal_height() const;
  void _internal_set_height(::uint32_t value);

  public:
  // optional uint32 width = 4 [(.validate.rules) = {
  bool has_width() const;
  void clear_width() ;
  ::uint32_t width() const;
  void set_width(::uint32_t value);

  private:
  ::uint32_t _internal_width() const;
  void _internal_set_width(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Genericvehicle& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t curbweight_;
    ::uint32_t length_;
    ::uint32_t height_;
    ::uint32_t width_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_covesa_2fads_5flf_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Genericvehicle_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Genericvehicle

// optional uint32 curbweight = 1 [(.validate.rules) = {
inline bool Genericvehicle::has_curbweight() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Genericvehicle::clear_curbweight() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.curbweight_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint32_t Genericvehicle::curbweight() const {
  // @@protoc_insertion_point(field_get:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle.curbweight)
  return _internal_curbweight();
}
inline void Genericvehicle::set_curbweight(::uint32_t value) {
  _internal_set_curbweight(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle.curbweight)
}
inline ::uint32_t Genericvehicle::_internal_curbweight() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.curbweight_;
}
inline void Genericvehicle::_internal_set_curbweight(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.curbweight_ = value;
}

// optional uint32 length = 2 [(.validate.rules) = {
inline bool Genericvehicle::has_length() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Genericvehicle::clear_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t Genericvehicle::length() const {
  // @@protoc_insertion_point(field_get:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle.length)
  return _internal_length();
}
inline void Genericvehicle::set_length(::uint32_t value) {
  _internal_set_length(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle.length)
}
inline ::uint32_t Genericvehicle::_internal_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.length_;
}
inline void Genericvehicle::_internal_set_length(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_ = value;
}

// optional uint32 height = 3 [(.validate.rules) = {
inline bool Genericvehicle::has_height() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Genericvehicle::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t Genericvehicle::height() const {
  // @@protoc_insertion_point(field_get:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle.height)
  return _internal_height();
}
inline void Genericvehicle::set_height(::uint32_t value) {
  _internal_set_height(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle.height)
}
inline ::uint32_t Genericvehicle::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void Genericvehicle::_internal_set_height(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// optional uint32 width = 4 [(.validate.rules) = {
inline bool Genericvehicle::has_width() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Genericvehicle::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::uint32_t Genericvehicle::width() const {
  // @@protoc_insertion_point(field_get:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle.width)
  return _internal_width();
}
inline void Genericvehicle::set_width(::uint32_t value) {
  _internal_set_width(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:COVESA.ADS_LF.TRUCK.VEHICLE.GENERICVEHICLE.Genericvehicle.width)
}
inline ::uint32_t Genericvehicle::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void Genericvehicle::_internal_set_width(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace GENERICVEHICLE
}  // namespace VEHICLE
}  // namespace TRUCK
}  // namespace ADS_LF
}  // namespace COVESA


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // covesa_2fads_5flf_2ftruck_2fvehicle_2fgenericvehicle_2fgenericvehicle_2eproto_2epb_2eh
