// Code generated by protoc-gen-validate
// source: ivdct/weight/weight.proto
// DO NOT EDIT!!!

#include "ivdct/weight/weight.pb.validate.h"

#include <google/protobuf/message.h>
#include <google/protobuf/util/time_util.h>
#include "re2/re2.h"

namespace pgv {

namespace protobuf = google::protobuf;
namespace protobuf_wkt = google::protobuf;

namespace validate {
using std::string;

// define the regex for a UUID once up-front
const re2::RE2 _uuidPattern("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

pgv::Validator<::IVDCT::WEIGHT::Weight> validator___IVDCT__WEIGHT__Weight(static_cast<bool(*)(const ::IVDCT::WEIGHT::Weight&, pgv::ValidationMsg*)>(::IVDCT::WEIGHT::Validate));


} // namespace validate
} // namespace pgv


namespace IVDCT {
namespace WEIGHT {


// Validate checks the field values on ::IVDCT::WEIGHT::Weight with the rules
// defined in the proto definition for this message. If any rules are
// violated, the return value is false and an error message is written to the
// input string argument.

	

	

	

	

        

	

	

	



bool Validate(const ::IVDCT::WEIGHT::Weight& m, pgv::ValidationMsg* err) {
	(void)m;
	(void)err;
	
	
	
		if (m.axle_weight().size() > 17) {
			{
std::ostringstream msg("invalid ");
msg << "WeightValidationError" << "." << "AxleWeight";
msg << ": " << "value must contain no more than 17 item(s)";
*err = msg.str();
return false;
}
		}
	

	

	
		for (int i = 0; i < m.axle_weight().size(); i++) {
			const auto& item = m.axle_weight().Get(i);
			(void)item;

			

			
	
	
	

	
	{
		pgv::ValidationMsg inner_err;
		if (true && !pgv::BaseValidator::AbstractCheckMessage(item, &inner_err)) {
			{
std::ostringstream msg("invalid ");
msg << "WeightValidationError" << "." << "AxleWeight";
msg << "[" << i << "]";
msg << ": " << "embedded message failed validation";
msg << " | caused by " << inner_err;
*err = msg.str();
return false;
}
		}
	}
	

		}
	
	

		
	return true;
}


} // namespace
} // namespace

