// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ivdct/weight/weight.proto
// Protobuf C++ Version: 6.31.1

#ifndef ivdct_2fweight_2fweight_2eproto_2epb_2eh
#define ivdct_2fweight_2fweight_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "validate/validate.pb.h"
#include "ivdct/weight/axle_weight/axle_weight.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ivdct_2fweight_2fweight_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ivdct_2fweight_2fweight_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ivdct_2fweight_2fweight_2eproto;
}  // extern "C"
namespace IVDCT {
namespace WEIGHT {
class Weight;
struct WeightDefaultTypeInternal;
extern WeightDefaultTypeInternal _Weight_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Weight_class_data_;
}  // namespace WEIGHT
}  // namespace IVDCT
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace IVDCT {
namespace WEIGHT {

// ===================================================================


// -------------------------------------------------------------------

class Weight final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:IVDCT.WEIGHT.Weight) */ {
 public:
  inline Weight() : Weight(nullptr) {}
  ~Weight() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Weight* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Weight));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Weight(::google::protobuf::internal::ConstantInitialized);

  inline Weight(const Weight& from) : Weight(nullptr, from) {}
  inline Weight(Weight&& from) noexcept
      : Weight(nullptr, ::std::move(from)) {}
  inline Weight& operator=(const Weight& from) {
    CopyFrom(from);
    return *this;
  }
  inline Weight& operator=(Weight&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Weight& default_instance() {
    return *reinterpret_cast<const Weight*>(
        &_Weight_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Weight& a, Weight& b) { a.Swap(&b); }
  inline void Swap(Weight* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Weight* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Weight* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Weight>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Weight& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Weight& from) { Weight::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Weight* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "IVDCT.WEIGHT.Weight"; }

 protected:
  explicit Weight(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Weight(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Weight& from);
  Weight(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Weight&& from) noexcept
      : Weight(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAxleWeightFieldNumber = 1,
  };
  // repeated .IVDCT.WEIGHT.AXLE_WEIGHT.Axle_weight axle_weight = 1 [(.validate.rules) = {
  int axle_weight_size() const;
  private:
  int _internal_axle_weight_size() const;

  public:
  void clear_axle_weight() ;
  ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight* PROTOBUF_NONNULL mutable_axle_weight(int index);
  ::google::protobuf::RepeatedPtrField<::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight>* PROTOBUF_NONNULL mutable_axle_weight();

  private:
  const ::google::protobuf::RepeatedPtrField<::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight>& _internal_axle_weight() const;
  ::google::protobuf::RepeatedPtrField<::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight>* PROTOBUF_NONNULL _internal_mutable_axle_weight();
  public:
  const ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight& axle_weight(int index) const;
  ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight* PROTOBUF_NONNULL add_axle_weight();
  const ::google::protobuf::RepeatedPtrField<::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight>& axle_weight() const;
  // @@protoc_insertion_point(class_scope:IVDCT.WEIGHT.Weight)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Weight& from_msg);
    ::google::protobuf::RepeatedPtrField< ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight > axle_weight_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ivdct_2fweight_2fweight_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Weight_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Weight

// repeated .IVDCT.WEIGHT.AXLE_WEIGHT.Axle_weight axle_weight = 1 [(.validate.rules) = {
inline int Weight::_internal_axle_weight_size() const {
  return _internal_axle_weight().size();
}
inline int Weight::axle_weight_size() const {
  return _internal_axle_weight_size();
}
inline ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight* PROTOBUF_NONNULL Weight::mutable_axle_weight(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:IVDCT.WEIGHT.Weight.axle_weight)
  return _internal_mutable_axle_weight()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight>* PROTOBUF_NONNULL Weight::mutable_axle_weight()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:IVDCT.WEIGHT.Weight.axle_weight)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_axle_weight();
}
inline const ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight& Weight::axle_weight(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:IVDCT.WEIGHT.Weight.axle_weight)
  return _internal_axle_weight().Get(index);
}
inline ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight* PROTOBUF_NONNULL Weight::add_axle_weight()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight* _add = _internal_mutable_axle_weight()->Add();
  // @@protoc_insertion_point(field_add:IVDCT.WEIGHT.Weight.axle_weight)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight>& Weight::axle_weight() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:IVDCT.WEIGHT.Weight.axle_weight)
  return _internal_axle_weight();
}
inline const ::google::protobuf::RepeatedPtrField<::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight>&
Weight::_internal_axle_weight() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.axle_weight_;
}
inline ::google::protobuf::RepeatedPtrField<::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight>* PROTOBUF_NONNULL
Weight::_internal_mutable_axle_weight() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.axle_weight_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace WEIGHT
}  // namespace IVDCT


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ivdct_2fweight_2fweight_2eproto_2epb_2eh
