// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: covesa/dms/truck/truck.proto
// Protobuf C++ Version: 6.31.1

#include "covesa/dms/truck/truck.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace COVESA {
namespace DMS {
namespace TRUCK {

inline constexpr Truck::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : adas_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Truck::Truck(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Truck_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TruckDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TruckDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TruckDefaultTypeInternal() {}
  union {
    Truck _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TruckDefaultTypeInternal _Truck_default_instance_;
}  // namespace TRUCK
}  // namespace DMS
}  // namespace COVESA
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_covesa_2fdms_2ftruck_2ftruck_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_covesa_2fdms_2ftruck_2ftruck_2eproto = nullptr;
const ::uint32_t
    TableStruct_covesa_2fdms_2ftruck_2ftruck_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::COVESA::DMS::TRUCK::Truck, _impl_.adas_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::COVESA::DMS::TRUCK::Truck)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::COVESA::DMS::TRUCK::_Truck_default_instance_._instance,
};
const char descriptor_table_protodef_covesa_2fdms_2ftruck_2ftruck_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\034covesa/dms/truck/truck.proto\022\020COVESA.D"
    "MS.TRUCK\032 covesa/dms/truck/adas/adas.pro"
    "to\"2\n\005Truck\022)\n\004adas\030\001 \003(\0132\033.COVESA.DMS.T"
    "RUCK.ADAS.Adasb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_covesa_2fdms_2ftruck_2ftruck_2eproto_deps[1] = {
        &::descriptor_table_covesa_2fdms_2ftruck_2fadas_2fadas_2eproto,
};
static ::absl::once_flag descriptor_table_covesa_2fdms_2ftruck_2ftruck_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_covesa_2fdms_2ftruck_2ftruck_2eproto = {
    false,
    false,
    142,
    descriptor_table_protodef_covesa_2fdms_2ftruck_2ftruck_2eproto,
    "covesa/dms/truck/truck.proto",
    &descriptor_table_covesa_2fdms_2ftruck_2ftruck_2eproto_once,
    descriptor_table_covesa_2fdms_2ftruck_2ftruck_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_covesa_2fdms_2ftruck_2ftruck_2eproto::offsets,
    file_level_enum_descriptors_covesa_2fdms_2ftruck_2ftruck_2eproto,
    file_level_service_descriptors_covesa_2fdms_2ftruck_2ftruck_2eproto,
};
namespace COVESA {
namespace DMS {
namespace TRUCK {
// ===================================================================

class Truck::_Internal {
 public:
};

void Truck::clear_adas() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.adas_.Clear();
}
Truck::Truck(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Truck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:COVESA.DMS.TRUCK.Truck)
}
PROTOBUF_NDEBUG_INLINE Truck::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::COVESA::DMS::TRUCK::Truck& from_msg)
      : adas_{visibility, arena, from.adas_},
        _cached_size_{0} {}

Truck::Truck(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Truck& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Truck_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Truck* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:COVESA.DMS.TRUCK.Truck)
}
PROTOBUF_NDEBUG_INLINE Truck::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : adas_{visibility, arena},
        _cached_size_{0} {}

inline void Truck::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Truck::~Truck() {
  // @@protoc_insertion_point(destructor:COVESA.DMS.TRUCK.Truck)
  SharedDtor(*this);
}
inline void Truck::SharedDtor(MessageLite& self) {
  Truck& this_ = static_cast<Truck&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Truck::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Truck(arena);
}
constexpr auto Truck::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Truck, _impl_.adas_) +
          decltype(Truck::_impl_.adas_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Truck), alignof(Truck), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Truck::PlacementNew_,
                                 sizeof(Truck),
                                 alignof(Truck));
  }
}
constexpr auto Truck::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Truck_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Truck::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Truck>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Truck::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Truck>(), &Truck::ByteSizeLong,
              &Truck::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Truck, _impl_._cached_size_),
          false,
      },
      &Truck::kDescriptorMethods,
      &descriptor_table_covesa_2fdms_2ftruck_2ftruck_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Truck_class_data_ =
        Truck::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Truck::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Truck_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Truck_class_data_.tc_table);
  return Truck_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
Truck::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Truck_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::COVESA::DMS::TRUCK::Truck>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .COVESA.DMS.TRUCK.ADAS.Adas adas = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Truck, _impl_.adas_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .COVESA.DMS.TRUCK.ADAS.Adas adas = 1;
    {PROTOBUF_FIELD_OFFSET(Truck, _impl_.adas_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::COVESA::DMS::TRUCK::ADAS::Adas>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Truck::Clear() {
// @@protoc_insertion_point(message_clear_start:COVESA.DMS.TRUCK.Truck)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.adas_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Truck::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Truck& this_ = static_cast<const Truck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Truck::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Truck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:COVESA.DMS.TRUCK.Truck)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .COVESA.DMS.TRUCK.ADAS.Adas adas = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_adas_size());
       i < n; i++) {
    const auto& repfield = this_._internal_adas().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:COVESA.DMS.TRUCK.Truck)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Truck::ByteSizeLong(const MessageLite& base) {
  const Truck& this_ = static_cast<const Truck&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Truck::ByteSizeLong() const {
  const Truck& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:COVESA.DMS.TRUCK.Truck)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .COVESA.DMS.TRUCK.ADAS.Adas adas = 1;
    {
      total_size += 1UL * this_._internal_adas_size();
      for (const auto& msg : this_._internal_adas()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Truck::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Truck*>(&to_msg);
  auto& from = static_cast<const Truck&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:COVESA.DMS.TRUCK.Truck)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_adas()->MergeFrom(
      from._internal_adas());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Truck::CopyFrom(const Truck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:COVESA.DMS.TRUCK.Truck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Truck::InternalSwap(Truck* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.adas_.InternalSwap(&other->_impl_.adas_);
}

::google::protobuf::Metadata Truck::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace TRUCK
}  // namespace DMS
}  // namespace COVESA
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_covesa_2fdms_2ftruck_2ftruck_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
