// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ads_lf/vehicle/width/width.proto
// Protobuf C++ Version: 6.31.1

#ifndef ads_5flf_2fvehicle_2fwidth_2fwidth_2eproto_2epb_2eh
#define ads_5flf_2fvehicle_2fwidth_2fwidth_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "validate/validate.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ads_5flf_2fvehicle_2fwidth_2fwidth_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ads_5flf_2fvehicle_2fwidth_2fwidth_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ads_5flf_2fvehicle_2fwidth_2fwidth_2eproto;
}  // extern "C"
namespace ADS_LF {
namespace VEHICLE {
namespace WIDTH {
class Width;
struct WidthDefaultTypeInternal;
extern WidthDefaultTypeInternal _Width_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Width_class_data_;
}  // namespace WIDTH
}  // namespace VEHICLE
}  // namespace ADS_LF
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ADS_LF {
namespace VEHICLE {
namespace WIDTH {

// ===================================================================


// -------------------------------------------------------------------

class Width final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ADS_LF.VEHICLE.WIDTH.Width) */ {
 public:
  inline Width() : Width(nullptr) {}
  ~Width() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Width* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Width));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Width(::google::protobuf::internal::ConstantInitialized);

  inline Width(const Width& from) : Width(nullptr, from) {}
  inline Width(Width&& from) noexcept
      : Width(nullptr, ::std::move(from)) {}
  inline Width& operator=(const Width& from) {
    CopyFrom(from);
    return *this;
  }
  inline Width& operator=(Width&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Width& default_instance() {
    return *reinterpret_cast<const Width*>(
        &_Width_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Width& a, Width& b) { a.Swap(&b); }
  inline void Swap(Width* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Width* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Width* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Width>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Width& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Width& from) { Width::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Width* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ADS_LF.VEHICLE.WIDTH.Width"; }

 protected:
  explicit Width(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Width(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Width& from);
  Width(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Width&& from) noexcept
      : Width(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLeftFieldNumber = 2,
    kRightFieldNumber = 3,
    kTotalFieldNumber = 1,
  };
  // optional uint64 left = 2 [(.validate.rules) = {
  bool has_left() const;
  void clear_left() ;
  ::uint64_t left() const;
  void set_left(::uint64_t value);

  private:
  ::uint64_t _internal_left() const;
  void _internal_set_left(::uint64_t value);

  public:
  // optional uint64 right = 3 [(.validate.rules) = {
  bool has_right() const;
  void clear_right() ;
  ::uint64_t right() const;
  void set_right(::uint64_t value);

  private:
  ::uint64_t _internal_right() const;
  void _internal_set_right(::uint64_t value);

  public:
  // optional uint32 total = 1 [(.validate.rules) = {
  bool has_total() const;
  void clear_total() ;
  ::uint32_t total() const;
  void set_total(::uint32_t value);

  private:
  ::uint32_t _internal_total() const;
  void _internal_set_total(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ADS_LF.VEHICLE.WIDTH.Width)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Width& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t left_;
    ::uint64_t right_;
    ::uint32_t total_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ads_5flf_2fvehicle_2fwidth_2fwidth_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Width_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Width

// optional uint32 total = 1 [(.validate.rules) = {
inline bool Width::has_total() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Width::clear_total() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::uint32_t Width::total() const {
  // @@protoc_insertion_point(field_get:ADS_LF.VEHICLE.WIDTH.Width.total)
  return _internal_total();
}
inline void Width::set_total(::uint32_t value) {
  _internal_set_total(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:ADS_LF.VEHICLE.WIDTH.Width.total)
}
inline ::uint32_t Width::_internal_total() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_;
}
inline void Width::_internal_set_total(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_ = value;
}

// optional uint64 left = 2 [(.validate.rules) = {
inline bool Width::has_left() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Width::clear_left() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t Width::left() const {
  // @@protoc_insertion_point(field_get:ADS_LF.VEHICLE.WIDTH.Width.left)
  return _internal_left();
}
inline void Width::set_left(::uint64_t value) {
  _internal_set_left(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:ADS_LF.VEHICLE.WIDTH.Width.left)
}
inline ::uint64_t Width::_internal_left() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.left_;
}
inline void Width::_internal_set_left(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.left_ = value;
}

// optional uint64 right = 3 [(.validate.rules) = {
inline bool Width::has_right() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Width::clear_right() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint64_t Width::right() const {
  // @@protoc_insertion_point(field_get:ADS_LF.VEHICLE.WIDTH.Width.right)
  return _internal_right();
}
inline void Width::set_right(::uint64_t value) {
  _internal_set_right(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:ADS_LF.VEHICLE.WIDTH.Width.right)
}
inline ::uint64_t Width::_internal_right() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.right_;
}
inline void Width::_internal_set_right(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.right_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace WIDTH
}  // namespace VEHICLE
}  // namespace ADS_LF


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ads_5flf_2fvehicle_2fwidth_2fwidth_2eproto_2epb_2eh
