// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: covesa/covesa.proto
// Protobuf C++ Version: 6.31.1

#include "covesa/covesa.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace COVESA {

inline constexpr Covesa::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ads_lf_{nullptr},
        ads_hf_{nullptr},
        dms_{nullptr},
        hub_hf_{nullptr},
        ivdct_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Covesa::Covesa(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Covesa_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CovesaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CovesaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CovesaDefaultTypeInternal() {}
  union {
    Covesa _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CovesaDefaultTypeInternal _Covesa_default_instance_;
}  // namespace COVESA
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_covesa_2fcovesa_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_covesa_2fcovesa_2eproto = nullptr;
const ::uint32_t
    TableStruct_covesa_2fcovesa_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::COVESA::Covesa, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::COVESA::Covesa, _impl_.ads_lf_),
        PROTOBUF_FIELD_OFFSET(::COVESA::Covesa, _impl_.ads_hf_),
        PROTOBUF_FIELD_OFFSET(::COVESA::Covesa, _impl_.dms_),
        PROTOBUF_FIELD_OFFSET(::COVESA::Covesa, _impl_.hub_hf_),
        PROTOBUF_FIELD_OFFSET(::COVESA::Covesa, _impl_.ivdct_),
        0,
        1,
        2,
        3,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::COVESA::Covesa)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::COVESA::_Covesa_default_instance_._instance,
};
const char descriptor_table_protodef_covesa_2fcovesa_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023covesa/covesa.proto\022\006COVESA\032\032covesa/ad"
    "s_lf/ads_lf.proto\032\032covesa/ads_hf/ads_hf."
    "proto\032\024covesa/dms/dms.proto\032\032covesa/hub_"
    "hf/hub_hf.proto\032\030covesa/ivdct/ivdct.prot"
    "o\"\213\002\n\006Covesa\022*\n\006ads_lf\030\001 \001(\0132\025.COVESA.AD"
    "S_LF.Ads_lfH\000\210\001\001\022*\n\006ads_hf\030\002 \001(\0132\025.COVES"
    "A.ADS_HF.Ads_hfH\001\210\001\001\022!\n\003dms\030\003 \001(\0132\017.COVE"
    "SA.DMS.DmsH\002\210\001\001\022*\n\006hub_hf\030\004 \001(\0132\025.COVESA"
    ".HUB_HF.Hub_hfH\003\210\001\001\022\'\n\005ivdct\030\005 \001(\0132\023.COV"
    "ESA.IVDCT.IvdctH\004\210\001\001B\t\n\007_ads_lfB\t\n\007_ads_"
    "hfB\006\n\004_dmsB\t\n\007_hub_hfB\010\n\006_ivdctb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_covesa_2fcovesa_2eproto_deps[5] = {
        &::descriptor_table_covesa_2fads_5fhf_2fads_5fhf_2eproto,
        &::descriptor_table_covesa_2fads_5flf_2fads_5flf_2eproto,
        &::descriptor_table_covesa_2fdms_2fdms_2eproto,
        &::descriptor_table_covesa_2fhub_5fhf_2fhub_5fhf_2eproto,
        &::descriptor_table_covesa_2fivdct_2fivdct_2eproto,
};
static ::absl::once_flag descriptor_table_covesa_2fcovesa_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_covesa_2fcovesa_2eproto = {
    false,
    false,
    439,
    descriptor_table_protodef_covesa_2fcovesa_2eproto,
    "covesa/covesa.proto",
    &descriptor_table_covesa_2fcovesa_2eproto_once,
    descriptor_table_covesa_2fcovesa_2eproto_deps,
    5,
    1,
    schemas,
    file_default_instances,
    TableStruct_covesa_2fcovesa_2eproto::offsets,
    file_level_enum_descriptors_covesa_2fcovesa_2eproto,
    file_level_service_descriptors_covesa_2fcovesa_2eproto,
};
namespace COVESA {
// ===================================================================

class Covesa::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Covesa>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Covesa, _impl_._has_bits_);
};

void Covesa::clear_ads_lf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ads_lf_ != nullptr) _impl_.ads_lf_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
void Covesa::clear_ads_hf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ads_hf_ != nullptr) _impl_.ads_hf_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
void Covesa::clear_dms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.dms_ != nullptr) _impl_.dms_->Clear();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
void Covesa::clear_hub_hf() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.hub_hf_ != nullptr) _impl_.hub_hf_->Clear();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
void Covesa::clear_ivdct() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ivdct_ != nullptr) _impl_.ivdct_->Clear();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
Covesa::Covesa(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Covesa_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:COVESA.Covesa)
}
PROTOBUF_NDEBUG_INLINE Covesa::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::COVESA::Covesa& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Covesa::Covesa(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Covesa& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Covesa_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Covesa* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.ads_lf_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ads_lf_)
                : nullptr;
  _impl_.ads_hf_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ads_hf_)
                : nullptr;
  _impl_.dms_ = ((cached_has_bits & 0x00000004u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.dms_)
                : nullptr;
  _impl_.hub_hf_ = ((cached_has_bits & 0x00000008u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.hub_hf_)
                : nullptr;
  _impl_.ivdct_ = ((cached_has_bits & 0x00000010u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ivdct_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:COVESA.Covesa)
}
PROTOBUF_NDEBUG_INLINE Covesa::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Covesa::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, ads_lf_),
           0,
           offsetof(Impl_, ivdct_) -
               offsetof(Impl_, ads_lf_) +
               sizeof(Impl_::ivdct_));
}
Covesa::~Covesa() {
  // @@protoc_insertion_point(destructor:COVESA.Covesa)
  SharedDtor(*this);
}
inline void Covesa::SharedDtor(MessageLite& self) {
  Covesa& this_ = static_cast<Covesa&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.ads_lf_;
  delete this_._impl_.ads_hf_;
  delete this_._impl_.dms_;
  delete this_._impl_.hub_hf_;
  delete this_._impl_.ivdct_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Covesa::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Covesa(arena);
}
constexpr auto Covesa::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Covesa),
                                            alignof(Covesa));
}
constexpr auto Covesa::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Covesa_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Covesa::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Covesa>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Covesa::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Covesa>(), &Covesa::ByteSizeLong,
              &Covesa::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Covesa, _impl_._cached_size_),
          false,
      },
      &Covesa::kDescriptorMethods,
      &descriptor_table_covesa_2fcovesa_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Covesa_class_data_ =
        Covesa::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Covesa::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Covesa_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Covesa_class_data_.tc_table);
  return Covesa_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 5, 0, 2>
Covesa::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Covesa, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    5,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Covesa_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::COVESA::Covesa>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional .COVESA.ADS_LF.Ads_lf ads_lf = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Covesa, _impl_.ads_lf_)}},
    // optional .COVESA.ADS_HF.Ads_hf ads_hf = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(Covesa, _impl_.ads_hf_)}},
    // optional .COVESA.DMS.Dms dms = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 2, 2, PROTOBUF_FIELD_OFFSET(Covesa, _impl_.dms_)}},
    // optional .COVESA.HUB_HF.Hub_hf hub_hf = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 3, 3, PROTOBUF_FIELD_OFFSET(Covesa, _impl_.hub_hf_)}},
    // optional .COVESA.IVDCT.Ivdct ivdct = 5;
    {::_pbi::TcParser::FastMtS1,
     {42, 4, 4, PROTOBUF_FIELD_OFFSET(Covesa, _impl_.ivdct_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .COVESA.ADS_LF.Ads_lf ads_lf = 1;
    {PROTOBUF_FIELD_OFFSET(Covesa, _impl_.ads_lf_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .COVESA.ADS_HF.Ads_hf ads_hf = 2;
    {PROTOBUF_FIELD_OFFSET(Covesa, _impl_.ads_hf_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .COVESA.DMS.Dms dms = 3;
    {PROTOBUF_FIELD_OFFSET(Covesa, _impl_.dms_), _Internal::kHasBitsOffset + 2, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .COVESA.HUB_HF.Hub_hf hub_hf = 4;
    {PROTOBUF_FIELD_OFFSET(Covesa, _impl_.hub_hf_), _Internal::kHasBitsOffset + 3, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional .COVESA.IVDCT.Ivdct ivdct = 5;
    {PROTOBUF_FIELD_OFFSET(Covesa, _impl_.ivdct_), _Internal::kHasBitsOffset + 4, 4,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::COVESA::ADS_LF::Ads_lf>()},
      {::_pbi::TcParser::GetTable<::COVESA::ADS_HF::Ads_hf>()},
      {::_pbi::TcParser::GetTable<::COVESA::DMS::Dms>()},
      {::_pbi::TcParser::GetTable<::COVESA::HUB_HF::Hub_hf>()},
      {::_pbi::TcParser::GetTable<::COVESA::IVDCT::Ivdct>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Covesa::Clear() {
// @@protoc_insertion_point(message_clear_start:COVESA.Covesa)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(_impl_.ads_lf_ != nullptr);
      _impl_.ads_lf_->Clear();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.ads_hf_ != nullptr);
      _impl_.ads_hf_->Clear();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(_impl_.dms_ != nullptr);
      _impl_.dms_->Clear();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(_impl_.hub_hf_ != nullptr);
      _impl_.hub_hf_->Clear();
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      ABSL_DCHECK(_impl_.ivdct_ != nullptr);
      _impl_.ivdct_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Covesa::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Covesa& this_ = static_cast<const Covesa&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Covesa::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Covesa& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:COVESA.Covesa)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .COVESA.ADS_LF.Ads_lf ads_lf = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.ads_lf_, this_._impl_.ads_lf_->GetCachedSize(), target,
        stream);
  }

  // optional .COVESA.ADS_HF.Ads_hf ads_hf = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.ads_hf_, this_._impl_.ads_hf_->GetCachedSize(), target,
        stream);
  }

  // optional .COVESA.DMS.Dms dms = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.dms_, this_._impl_.dms_->GetCachedSize(), target,
        stream);
  }

  // optional .COVESA.HUB_HF.Hub_hf hub_hf = 4;
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.hub_hf_, this_._impl_.hub_hf_->GetCachedSize(), target,
        stream);
  }

  // optional .COVESA.IVDCT.Ivdct ivdct = 5;
  if ((cached_has_bits & 0x00000010u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.ivdct_, this_._impl_.ivdct_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:COVESA.Covesa)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Covesa::ByteSizeLong(const MessageLite& base) {
  const Covesa& this_ = static_cast<const Covesa&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Covesa::ByteSizeLong() const {
  const Covesa& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:COVESA.Covesa)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // optional .COVESA.ADS_LF.Ads_lf ads_lf = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ads_lf_);
    }
    // optional .COVESA.ADS_HF.Ads_hf ads_hf = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ads_hf_);
    }
    // optional .COVESA.DMS.Dms dms = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.dms_);
    }
    // optional .COVESA.HUB_HF.Hub_hf hub_hf = 4;
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.hub_hf_);
    }
    // optional .COVESA.IVDCT.Ivdct ivdct = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ivdct_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Covesa::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Covesa*>(&to_msg);
  auto& from = static_cast<const Covesa&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:COVESA.Covesa)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.ads_lf_ != nullptr);
      if (_this->_impl_.ads_lf_ == nullptr) {
        _this->_impl_.ads_lf_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ads_lf_);
      } else {
        _this->_impl_.ads_lf_->MergeFrom(*from._impl_.ads_lf_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.ads_hf_ != nullptr);
      if (_this->_impl_.ads_hf_ == nullptr) {
        _this->_impl_.ads_hf_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ads_hf_);
      } else {
        _this->_impl_.ads_hf_->MergeFrom(*from._impl_.ads_hf_);
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      ABSL_DCHECK(from._impl_.dms_ != nullptr);
      if (_this->_impl_.dms_ == nullptr) {
        _this->_impl_.dms_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.dms_);
      } else {
        _this->_impl_.dms_->MergeFrom(*from._impl_.dms_);
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      ABSL_DCHECK(from._impl_.hub_hf_ != nullptr);
      if (_this->_impl_.hub_hf_ == nullptr) {
        _this->_impl_.hub_hf_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.hub_hf_);
      } else {
        _this->_impl_.hub_hf_->MergeFrom(*from._impl_.hub_hf_);
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      ABSL_DCHECK(from._impl_.ivdct_ != nullptr);
      if (_this->_impl_.ivdct_ == nullptr) {
        _this->_impl_.ivdct_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ivdct_);
      } else {
        _this->_impl_.ivdct_->MergeFrom(*from._impl_.ivdct_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Covesa::CopyFrom(const Covesa& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:COVESA.Covesa)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Covesa::InternalSwap(Covesa* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Covesa, _impl_.ivdct_)
      + sizeof(Covesa::_impl_.ivdct_)
      - PROTOBUF_FIELD_OFFSET(Covesa, _impl_.ads_lf_)>(
          reinterpret_cast<char*>(&_impl_.ads_lf_),
          reinterpret_cast<char*>(&other->_impl_.ads_lf_));
}

::google::protobuf::Metadata Covesa::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace COVESA
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_covesa_2fcovesa_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
