// Code generated by protoc-gen-validate
// source: visa/testmessage00/testmessage00.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "visa/testmessage00/testmessage00.pb.h"


namespace VISA {
namespace TestMessage00 {

using std::string;


extern bool Validate(const ::VISA::TestMessage00::TestMessage00& m, pgv::ValidationMsg* err);

extern bool Validate(const ::VISA::TestMessage00::TestMessage00_Header& m, pgv::ValidationMsg* err);

extern bool Validate(const ::VISA::TestMessage00::TestMessage00_REGION& m, pgv::ValidationMsg* err);

extern bool Validate(const ::VISA::TestMessage00::TestMessage00_REGION_Reg_TestMessage00& m, pgv::ValidationMsg* err);


} // namespace
} // namespace


#define X_VISA_TESTMESSAGE00_TESTMESSAGE_00(X) \
X(::VISA::TestMessage00::TestMessage00) \
X(::VISA::TestMessage00::TestMessage00_Header) \
X(::VISA::TestMessage00::TestMessage00_REGION) \
X(::VISA::TestMessage00::TestMessage00_REGION_Reg_TestMessage00) \

