// Code generated by protoc-gen-validate
// source: ads_lf/system/system.proto
// DO NOT EDIT!!!

#include "ads_lf/system/system.pb.validate.h"

#include <google/protobuf/message.h>
#include <google/protobuf/util/time_util.h>
#include "re2/re2.h"

namespace pgv {

namespace protobuf = google::protobuf;
namespace protobuf_wkt = google::protobuf;

namespace validate {
using std::string;

// define the regex for a UUID once up-front
const re2::RE2 _uuidPattern("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

pgv::Validator<::ADS_LF::SYSTEM::System> validator___ADS_LF__SYSTEM__System(static_cast<bool(*)(const ::ADS_LF::SYSTEM::System&, pgv::ValidationMsg*)>(::ADS_LF::SYSTEM::Validate));


} // namespace validate
} // namespace pgv


namespace ADS_LF {
namespace SYSTEM {


// Validate checks the field values on ::ADS_LF::SYSTEM::System with the rules
// defined in the proto definition for this message. If any rules are
// violated, the return value is false and an error message is written to the
// input string argument.

	

	

	

	

        

	

	

	



bool Validate(const ::ADS_LF::SYSTEM::System& m, pgv::ValidationMsg* err) {
	(void)m;
	(void)err;
			if (m.has_supported()) {
				
	
	
	

	
	{
		pgv::ValidationMsg inner_err;
		if (m.has_supported() && !pgv::BaseValidator::AbstractCheckMessage(m.supported(), &inner_err)) {
			{
std::ostringstream msg("invalid ");
msg << "SystemValidationError" << "." << "Supported";
msg << ": " << "embedded message failed validation";
msg << " | caused by " << inner_err;
*err = msg.str();
return false;
}
		}
	}
	

			}
		
		
	return true;
}


} // namespace
} // namespace

