// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ads_lf/controller/controller.proto
// Protobuf C++ Version: 6.31.1

#ifndef ads_5flf_2fcontroller_2fcontroller_2eproto_2epb_2eh
#define ads_5flf_2fcontroller_2fcontroller_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "validate/validate.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ads_5flf_2fcontroller_2fcontroller_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ads_5flf_2fcontroller_2fcontroller_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ads_5flf_2fcontroller_2fcontroller_2eproto;
}  // extern "C"
namespace ADS_LF {
namespace CONTROLLER {
enum Controller_Status : int;
extern const uint32_t Controller_Status_internal_data_[];
enum Controller_Type : int;
extern const uint32_t Controller_Type_internal_data_[];
class Controller;
struct ControllerDefaultTypeInternal;
extern ControllerDefaultTypeInternal _Controller_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Controller_class_data_;
}  // namespace CONTROLLER
}  // namespace ADS_LF
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::ADS_LF::CONTROLLER::Controller_Status_internal_data_>
    internal::EnumTraitsImpl::value<::ADS_LF::CONTROLLER::Controller_Status>;
template <>
internal::EnumTraitsT<::ADS_LF::CONTROLLER::Controller_Type_internal_data_>
    internal::EnumTraitsImpl::value<::ADS_LF::CONTROLLER::Controller_Type>;
}  // namespace protobuf
}  // namespace google

namespace ADS_LF {
namespace CONTROLLER {
enum Controller_Type : int {
  Controller_Type_TYPE_UNKNOWN = 0,
  Controller_Type_ADS = 1,
  Controller_Type_OTHER = 2,
  Controller_Type_Controller_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Controller_Type_Controller_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Controller_Type_internal_data_[];
inline constexpr Controller_Type Controller_Type_Type_MIN =
    static_cast<Controller_Type>(0);
inline constexpr Controller_Type Controller_Type_Type_MAX =
    static_cast<Controller_Type>(2);
inline bool Controller_Type_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Controller_Type_Type_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Controller_Type_descriptor();
template <typename T>
const ::std::string& Controller_Type_Name(T value) {
  static_assert(::std::is_same<T, Controller_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return Controller_Type_Name(static_cast<Controller_Type>(value));
}
template <>
inline const ::std::string& Controller_Type_Name(Controller_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Controller_Type_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Controller_Type_Parse(
    ::absl::string_view name, Controller_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Controller_Type>(Controller_Type_descriptor(), name,
                                           value);
}
enum Controller_Status : int {
  Controller_Status_STATUS_UNKNOWN = 0,
  Controller_Status_STATUS_OK = 1,
  Controller_Status_STATUS_FAIL = 2,
  Controller_Status_Controller_Status_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Controller_Status_Controller_Status_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Controller_Status_internal_data_[];
inline constexpr Controller_Status Controller_Status_Status_MIN =
    static_cast<Controller_Status>(0);
inline constexpr Controller_Status Controller_Status_Status_MAX =
    static_cast<Controller_Status>(2);
inline bool Controller_Status_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Controller_Status_Status_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Controller_Status_descriptor();
template <typename T>
const ::std::string& Controller_Status_Name(T value) {
  static_assert(::std::is_same<T, Controller_Status>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Status_Name().");
  return Controller_Status_Name(static_cast<Controller_Status>(value));
}
template <>
inline const ::std::string& Controller_Status_Name(Controller_Status value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Controller_Status_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Controller_Status_Parse(
    ::absl::string_view name, Controller_Status* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Controller_Status>(Controller_Status_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class Controller final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ADS_LF.CONTROLLER.Controller) */ {
 public:
  inline Controller() : Controller(nullptr) {}
  ~Controller() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Controller* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Controller));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Controller(::google::protobuf::internal::ConstantInitialized);

  inline Controller(const Controller& from) : Controller(nullptr, from) {}
  inline Controller(Controller&& from) noexcept
      : Controller(nullptr, ::std::move(from)) {}
  inline Controller& operator=(const Controller& from) {
    CopyFrom(from);
    return *this;
  }
  inline Controller& operator=(Controller&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Controller& default_instance() {
    return *reinterpret_cast<const Controller*>(
        &_Controller_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Controller& a, Controller& b) { a.Swap(&b); }
  inline void Swap(Controller* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Controller* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Controller* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Controller>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Controller& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Controller& from) { Controller::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Controller* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ADS_LF.CONTROLLER.Controller"; }

 protected:
  explicit Controller(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Controller(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Controller& from);
  Controller(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Controller&& from) noexcept
      : Controller(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Type = Controller_Type;
  static constexpr Type TYPE_UNKNOWN = Controller_Type_TYPE_UNKNOWN;
  static constexpr Type ADS = Controller_Type_ADS;
  static constexpr Type OTHER = Controller_Type_OTHER;
  static inline bool Type_IsValid(int value) {
    return Controller_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = Controller_Type_Type_MIN;
  static constexpr Type Type_MAX = Controller_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = Controller_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Type_descriptor() {
    return Controller_Type_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Type_Name(T value) {
    return Controller_Type_Name(value);
  }
  static inline bool Type_Parse(
      ::absl::string_view name, Type* PROTOBUF_NONNULL value) {
    return Controller_Type_Parse(name, value);
  }
  using Status = Controller_Status;
  static constexpr Status STATUS_UNKNOWN = Controller_Status_STATUS_UNKNOWN;
  static constexpr Status STATUS_OK = Controller_Status_STATUS_OK;
  static constexpr Status STATUS_FAIL = Controller_Status_STATUS_FAIL;
  static inline bool Status_IsValid(int value) {
    return Controller_Status_IsValid(value);
  }
  static constexpr Status Status_MIN = Controller_Status_Status_MIN;
  static constexpr Status Status_MAX = Controller_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE = Controller_Status_Status_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_descriptor() {
    return Controller_Status_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Status_Name(T value) {
    return Controller_Status_Name(value);
  }
  static inline bool Status_Parse(
      ::absl::string_view name, Status* PROTOBUF_NONNULL value) {
    return Controller_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 2,
    kTimestampFieldNumber = 1,
    kTypeFieldNumber = 3,
    kStatusFieldNumber = 4,
  };
  // optional string id = 2 [(.validate.rules) = {
  bool has_id() const;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // optional uint64 timestamp = 1 [(.validate.rules) = {
  bool has_timestamp() const;
  void clear_timestamp() ;
  ::uint64_t timestamp() const;
  void set_timestamp(::uint64_t value);

  private:
  ::uint64_t _internal_timestamp() const;
  void _internal_set_timestamp(::uint64_t value);

  public:
  // optional .ADS_LF.CONTROLLER.Controller.Type type = 3 [(.validate.rules) = {
  bool has_type() const;
  void clear_type() ;
  ::ADS_LF::CONTROLLER::Controller_Type type() const;
  void set_type(::ADS_LF::CONTROLLER::Controller_Type value);

  private:
  ::ADS_LF::CONTROLLER::Controller_Type _internal_type() const;
  void _internal_set_type(::ADS_LF::CONTROLLER::Controller_Type value);

  public:
  // optional .ADS_LF.CONTROLLER.Controller.Status status = 4 [(.validate.rules) = {
  bool has_status() const;
  void clear_status() ;
  ::ADS_LF::CONTROLLER::Controller_Status status() const;
  void set_status(::ADS_LF::CONTROLLER::Controller_Status value);

  private:
  ::ADS_LF::CONTROLLER::Controller_Status _internal_status() const;
  void _internal_set_status(::ADS_LF::CONTROLLER::Controller_Status value);

  public:
  // @@protoc_insertion_point(class_scope:ADS_LF.CONTROLLER.Controller)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 39,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Controller& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::uint64_t timestamp_;
    int type_;
    int status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ads_5flf_2fcontroller_2fcontroller_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Controller_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Controller

// optional uint64 timestamp = 1 [(.validate.rules) = {
inline bool Controller::has_timestamp() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Controller::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint64_t Controller::timestamp() const {
  // @@protoc_insertion_point(field_get:ADS_LF.CONTROLLER.Controller.timestamp)
  return _internal_timestamp();
}
inline void Controller::set_timestamp(::uint64_t value) {
  _internal_set_timestamp(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:ADS_LF.CONTROLLER.Controller.timestamp)
}
inline ::uint64_t Controller::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void Controller::_internal_set_timestamp(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// optional string id = 2 [(.validate.rules) = {
inline bool Controller::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Controller::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Controller::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ADS_LF.CONTROLLER.Controller.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Controller::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ADS_LF.CONTROLLER.Controller.id)
}
inline ::std::string* PROTOBUF_NONNULL Controller::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:ADS_LF.CONTROLLER.Controller.id)
  return _s;
}
inline const ::std::string& Controller::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void Controller::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Controller::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Controller::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ADS_LF.CONTROLLER.Controller.id)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void Controller::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ADS_LF.CONTROLLER.Controller.id)
}

// optional .ADS_LF.CONTROLLER.Controller.Type type = 3 [(.validate.rules) = {
inline bool Controller::has_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Controller::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::ADS_LF::CONTROLLER::Controller_Type Controller::type() const {
  // @@protoc_insertion_point(field_get:ADS_LF.CONTROLLER.Controller.type)
  return _internal_type();
}
inline void Controller::set_type(::ADS_LF::CONTROLLER::Controller_Type value) {
  _internal_set_type(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:ADS_LF.CONTROLLER.Controller.type)
}
inline ::ADS_LF::CONTROLLER::Controller_Type Controller::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::ADS_LF::CONTROLLER::Controller_Type>(_impl_.type_);
}
inline void Controller::_internal_set_type(::ADS_LF::CONTROLLER::Controller_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// optional .ADS_LF.CONTROLLER.Controller.Status status = 4 [(.validate.rules) = {
inline bool Controller::has_status() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void Controller::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::ADS_LF::CONTROLLER::Controller_Status Controller::status() const {
  // @@protoc_insertion_point(field_get:ADS_LF.CONTROLLER.Controller.status)
  return _internal_status();
}
inline void Controller::set_status(::ADS_LF::CONTROLLER::Controller_Status value) {
  _internal_set_status(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:ADS_LF.CONTROLLER.Controller.status)
}
inline ::ADS_LF::CONTROLLER::Controller_Status Controller::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::ADS_LF::CONTROLLER::Controller_Status>(_impl_.status_);
}
inline void Controller::_internal_set_status(::ADS_LF::CONTROLLER::Controller_Status value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace CONTROLLER
}  // namespace ADS_LF


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ADS_LF::CONTROLLER::Controller_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::ADS_LF::CONTROLLER::Controller_Type>() {
  return ::ADS_LF::CONTROLLER::Controller_Type_descriptor();
}
template <>
struct is_proto_enum<::ADS_LF::CONTROLLER::Controller_Status> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::ADS_LF::CONTROLLER::Controller_Status>() {
  return ::ADS_LF::CONTROLLER::Controller_Status_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ads_5flf_2fcontroller_2fcontroller_2eproto_2epb_2eh
