// Code generated by protoc-gen-validate
// source: ivdct/driving/brake/brake.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "ivdct/driving/brake/brake.pb.h"


namespace IVDCT {
namespace DRIVING {
namespace BRAKE {

using std::string;


extern bool Validate(const ::IVDCT::DRIVING::BRAKE::Brake& m, pgv::ValidationMsg* err);


} // namespace
} // namespace
} // namespace


#define X_IVDCT_DRIVING_BRAKE_BRAKE(X) \
X(::IVDCT::DRIVING::BRAKE::Brake) \

