// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vh_lf/conn_status/conn_status.proto
// Protobuf C++ Version: 6.31.1

#ifndef vh_5flf_2fconn_5fstatus_2fconn_5fstatus_2eproto_2epb_2eh
#define vh_5flf_2fconn_5fstatus_2fconn_5fstatus_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "validate/validate.pb.h"
#include "vh_lf/conn_status/other/other.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_vh_5flf_2fconn_5fstatus_2fconn_5fstatus_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_vh_5flf_2fconn_5fstatus_2fconn_5fstatus_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_vh_5flf_2fconn_5fstatus_2fconn_5fstatus_2eproto;
}  // extern "C"
namespace VH_LF {
namespace CONN_STATUS {
enum ConnStatus_ConnectionState : int;
extern const uint32_t ConnStatus_ConnectionState_internal_data_[];
class ConnStatus;
struct ConnStatusDefaultTypeInternal;
extern ConnStatusDefaultTypeInternal _ConnStatus_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ConnStatus_class_data_;
}  // namespace CONN_STATUS
}  // namespace VH_LF
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState_internal_data_>
    internal::EnumTraitsImpl::value<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState>;
}  // namespace protobuf
}  // namespace google

namespace VH_LF {
namespace CONN_STATUS {
enum ConnStatus_ConnectionState : int {
  ConnStatus_ConnectionState_CONN_STATUS_UNKNOWN = 0,
  ConnStatus_ConnectionState_CONN_STATUS_OK = 1,
  ConnStatus_ConnectionState_CONN_STATUS_FAIL = 2,
  ConnStatus_ConnectionState_CONN_STATUS_NOT_INSTALLED = 3,
  ConnStatus_ConnectionState_ConnStatus_ConnectionState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ConnStatus_ConnectionState_ConnStatus_ConnectionState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ConnStatus_ConnectionState_internal_data_[];
inline constexpr ConnStatus_ConnectionState ConnStatus_ConnectionState_ConnectionState_MIN =
    static_cast<ConnStatus_ConnectionState>(0);
inline constexpr ConnStatus_ConnectionState ConnStatus_ConnectionState_ConnectionState_MAX =
    static_cast<ConnStatus_ConnectionState>(3);
inline bool ConnStatus_ConnectionState_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int ConnStatus_ConnectionState_ConnectionState_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ConnStatus_ConnectionState_descriptor();
template <typename T>
const ::std::string& ConnStatus_ConnectionState_Name(T value) {
  static_assert(::std::is_same<T, ConnStatus_ConnectionState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ConnectionState_Name().");
  return ConnStatus_ConnectionState_Name(static_cast<ConnStatus_ConnectionState>(value));
}
template <>
inline const ::std::string& ConnStatus_ConnectionState_Name(ConnStatus_ConnectionState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ConnStatus_ConnectionState_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool ConnStatus_ConnectionState_Parse(
    ::absl::string_view name, ConnStatus_ConnectionState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConnStatus_ConnectionState>(ConnStatus_ConnectionState_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class ConnStatus final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:VH_LF.CONN_STATUS.ConnStatus) */ {
 public:
  inline ConnStatus() : ConnStatus(nullptr) {}
  ~ConnStatus() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ConnStatus* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ConnStatus));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ConnStatus(::google::protobuf::internal::ConstantInitialized);

  inline ConnStatus(const ConnStatus& from) : ConnStatus(nullptr, from) {}
  inline ConnStatus(ConnStatus&& from) noexcept
      : ConnStatus(nullptr, ::std::move(from)) {}
  inline ConnStatus& operator=(const ConnStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline ConnStatus& operator=(ConnStatus&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ConnStatus& default_instance() {
    return *reinterpret_cast<const ConnStatus*>(
        &_ConnStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ConnStatus& a, ConnStatus& b) { a.Swap(&b); }
  inline void Swap(ConnStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ConnStatus* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ConnStatus* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ConnStatus>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ConnStatus& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ConnStatus& from) { ConnStatus::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ConnStatus* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "VH_LF.CONN_STATUS.ConnStatus"; }

 protected:
  explicit ConnStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ConnStatus(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ConnStatus& from);
  ConnStatus(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ConnStatus&& from) noexcept
      : ConnStatus(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using ConnectionState = ConnStatus_ConnectionState;
  static constexpr ConnectionState CONN_STATUS_UNKNOWN = ConnStatus_ConnectionState_CONN_STATUS_UNKNOWN;
  static constexpr ConnectionState CONN_STATUS_OK = ConnStatus_ConnectionState_CONN_STATUS_OK;
  static constexpr ConnectionState CONN_STATUS_FAIL = ConnStatus_ConnectionState_CONN_STATUS_FAIL;
  static constexpr ConnectionState CONN_STATUS_NOT_INSTALLED = ConnStatus_ConnectionState_CONN_STATUS_NOT_INSTALLED;
  static inline bool ConnectionState_IsValid(int value) {
    return ConnStatus_ConnectionState_IsValid(value);
  }
  static constexpr ConnectionState ConnectionState_MIN = ConnStatus_ConnectionState_ConnectionState_MIN;
  static constexpr ConnectionState ConnectionState_MAX = ConnStatus_ConnectionState_ConnectionState_MAX;
  static constexpr int ConnectionState_ARRAYSIZE = ConnStatus_ConnectionState_ConnectionState_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ConnectionState_descriptor() {
    return ConnStatus_ConnectionState_descriptor();
  }
  template <typename T>
  static inline const ::std::string& ConnectionState_Name(T value) {
    return ConnStatus_ConnectionState_Name(value);
  }
  static inline bool ConnectionState_Parse(
      ::absl::string_view name, ConnectionState* PROTOBUF_NONNULL value) {
    return ConnStatus_ConnectionState_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kOtherFieldNumber = 6,
    kHmiFieldNumber = 1,
    kAdsFieldNumber = 2,
    kDmsFieldNumber = 3,
    kIvdctFieldNumber = 4,
    kDtgFieldNumber = 5,
  };
  // repeated .VH_LF.CONN_STATUS.OTHER.Other other = 6 [(.validate.rules) = {
  int other_size() const;
  private:
  int _internal_other_size() const;

  public:
  void clear_other() ;
  ::VH_LF::CONN_STATUS::OTHER::Other* PROTOBUF_NONNULL mutable_other(int index);
  ::google::protobuf::RepeatedPtrField<::VH_LF::CONN_STATUS::OTHER::Other>* PROTOBUF_NONNULL mutable_other();

  private:
  const ::google::protobuf::RepeatedPtrField<::VH_LF::CONN_STATUS::OTHER::Other>& _internal_other() const;
  ::google::protobuf::RepeatedPtrField<::VH_LF::CONN_STATUS::OTHER::Other>* PROTOBUF_NONNULL _internal_mutable_other();
  public:
  const ::VH_LF::CONN_STATUS::OTHER::Other& other(int index) const;
  ::VH_LF::CONN_STATUS::OTHER::Other* PROTOBUF_NONNULL add_other();
  const ::google::protobuf::RepeatedPtrField<::VH_LF::CONN_STATUS::OTHER::Other>& other() const;
  // optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState hmi = 1 [(.validate.rules) = {
  bool has_hmi() const;
  void clear_hmi() ;
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState hmi() const;
  void set_hmi(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  private:
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState _internal_hmi() const;
  void _internal_set_hmi(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  public:
  // optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState ads = 2 [(.validate.rules) = {
  bool has_ads() const;
  void clear_ads() ;
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ads() const;
  void set_ads(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  private:
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState _internal_ads() const;
  void _internal_set_ads(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  public:
  // optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState dms = 3 [(.validate.rules) = {
  bool has_dms() const;
  void clear_dms() ;
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState dms() const;
  void set_dms(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  private:
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState _internal_dms() const;
  void _internal_set_dms(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  public:
  // optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState ivdct = 4 [(.validate.rules) = {
  bool has_ivdct() const;
  void clear_ivdct() ;
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ivdct() const;
  void set_ivdct(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  private:
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState _internal_ivdct() const;
  void _internal_set_ivdct(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  public:
  // optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState dtg = 5 [(.validate.rules) = {
  bool has_dtg() const;
  void clear_dtg() ;
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState dtg() const;
  void set_dtg(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  private:
  ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState _internal_dtg() const;
  void _internal_set_dtg(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value);

  public:
  // @@protoc_insertion_point(class_scope:VH_LF.CONN_STATUS.ConnStatus)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ConnStatus& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::VH_LF::CONN_STATUS::OTHER::Other > other_;
    int hmi_;
    int ads_;
    int dms_;
    int ivdct_;
    int dtg_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_vh_5flf_2fconn_5fstatus_2fconn_5fstatus_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ConnStatus_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ConnStatus

// optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState hmi = 1 [(.validate.rules) = {
inline bool ConnStatus::has_hmi() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void ConnStatus::clear_hmi() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hmi_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::hmi() const {
  // @@protoc_insertion_point(field_get:VH_LF.CONN_STATUS.ConnStatus.hmi)
  return _internal_hmi();
}
inline void ConnStatus::set_hmi(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  _internal_set_hmi(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:VH_LF.CONN_STATUS.ConnStatus.hmi)
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::_internal_hmi() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState>(_impl_.hmi_);
}
inline void ConnStatus::_internal_set_hmi(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hmi_ = value;
}

// optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState ads = 2 [(.validate.rules) = {
inline bool ConnStatus::has_ads() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void ConnStatus::clear_ads() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ads_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::ads() const {
  // @@protoc_insertion_point(field_get:VH_LF.CONN_STATUS.ConnStatus.ads)
  return _internal_ads();
}
inline void ConnStatus::set_ads(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  _internal_set_ads(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:VH_LF.CONN_STATUS.ConnStatus.ads)
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::_internal_ads() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState>(_impl_.ads_);
}
inline void ConnStatus::_internal_set_ads(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ads_ = value;
}

// optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState dms = 3 [(.validate.rules) = {
inline bool ConnStatus::has_dms() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void ConnStatus::clear_dms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dms_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::dms() const {
  // @@protoc_insertion_point(field_get:VH_LF.CONN_STATUS.ConnStatus.dms)
  return _internal_dms();
}
inline void ConnStatus::set_dms(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  _internal_set_dms(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:VH_LF.CONN_STATUS.ConnStatus.dms)
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::_internal_dms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState>(_impl_.dms_);
}
inline void ConnStatus::_internal_set_dms(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dms_ = value;
}

// optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState ivdct = 4 [(.validate.rules) = {
inline bool ConnStatus::has_ivdct() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void ConnStatus::clear_ivdct() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ivdct_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::ivdct() const {
  // @@protoc_insertion_point(field_get:VH_LF.CONN_STATUS.ConnStatus.ivdct)
  return _internal_ivdct();
}
inline void ConnStatus::set_ivdct(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  _internal_set_ivdct(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:VH_LF.CONN_STATUS.ConnStatus.ivdct)
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::_internal_ivdct() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState>(_impl_.ivdct_);
}
inline void ConnStatus::_internal_set_ivdct(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ivdct_ = value;
}

// optional .VH_LF.CONN_STATUS.ConnStatus.ConnectionState dtg = 5 [(.validate.rules) = {
inline bool ConnStatus::has_dtg() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void ConnStatus::clear_dtg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dtg_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::dtg() const {
  // @@protoc_insertion_point(field_get:VH_LF.CONN_STATUS.ConnStatus.dtg)
  return _internal_dtg();
}
inline void ConnStatus::set_dtg(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  _internal_set_dtg(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:VH_LF.CONN_STATUS.ConnStatus.dtg)
}
inline ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState ConnStatus::_internal_dtg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState>(_impl_.dtg_);
}
inline void ConnStatus::_internal_set_dtg(::VH_LF::CONN_STATUS::ConnStatus_ConnectionState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.dtg_ = value;
}

// repeated .VH_LF.CONN_STATUS.OTHER.Other other = 6 [(.validate.rules) = {
inline int ConnStatus::_internal_other_size() const {
  return _internal_other().size();
}
inline int ConnStatus::other_size() const {
  return _internal_other_size();
}
inline ::VH_LF::CONN_STATUS::OTHER::Other* PROTOBUF_NONNULL ConnStatus::mutable_other(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:VH_LF.CONN_STATUS.ConnStatus.other)
  return _internal_mutable_other()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::VH_LF::CONN_STATUS::OTHER::Other>* PROTOBUF_NONNULL ConnStatus::mutable_other()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:VH_LF.CONN_STATUS.ConnStatus.other)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_other();
}
inline const ::VH_LF::CONN_STATUS::OTHER::Other& ConnStatus::other(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:VH_LF.CONN_STATUS.ConnStatus.other)
  return _internal_other().Get(index);
}
inline ::VH_LF::CONN_STATUS::OTHER::Other* PROTOBUF_NONNULL ConnStatus::add_other()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::VH_LF::CONN_STATUS::OTHER::Other* _add = _internal_mutable_other()->Add();
  // @@protoc_insertion_point(field_add:VH_LF.CONN_STATUS.ConnStatus.other)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::VH_LF::CONN_STATUS::OTHER::Other>& ConnStatus::other() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:VH_LF.CONN_STATUS.ConnStatus.other)
  return _internal_other();
}
inline const ::google::protobuf::RepeatedPtrField<::VH_LF::CONN_STATUS::OTHER::Other>&
ConnStatus::_internal_other() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.other_;
}
inline ::google::protobuf::RepeatedPtrField<::VH_LF::CONN_STATUS::OTHER::Other>* PROTOBUF_NONNULL
ConnStatus::_internal_mutable_other() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.other_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace CONN_STATUS
}  // namespace VH_LF


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::VH_LF::CONN_STATUS::ConnStatus_ConnectionState>() {
  return ::VH_LF::CONN_STATUS::ConnStatus_ConnectionState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // vh_5flf_2fconn_5fstatus_2fconn_5fstatus_2eproto_2epb_2eh
