// Code generated by protoc-gen-validate
// source: vh_lf/conn_status/conn_status.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "vh_lf/conn_status/conn_status.pb.h"


namespace VH_LF {
namespace CONN_STATUS {

using std::string;


extern bool Validate(const ::VH_LF::CONN_STATUS::ConnStatus& m, pgv::ValidationMsg* err);


} // namespace
} // namespace


#define X_VH_LF_CONN_STATUS_CONN_STATUS(X) \
X(::VH_LF::CONN_STATUS::ConnStatus) \

