// Code generated by protoc-gen-validate
// source: covesa/hub_hf/hub_hf.proto
// DO NOT EDIT!!!

#include "covesa/hub_hf/hub_hf.pb.validate.h"

#include <google/protobuf/message.h>
#include <google/protobuf/util/time_util.h>
#include "re2/re2.h"

namespace pgv {

namespace protobuf = google::protobuf;
namespace protobuf_wkt = google::protobuf;

namespace validate {
using std::string;

// define the regex for a UUID once up-front
const re2::RE2 _uuidPattern("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

pgv::Validator<::COVESA::HUB_HF::Hub_hf> validator___COVESA__HUB_HF__Hub_hf(static_cast<bool(*)(const ::COVESA::HUB_HF::Hub_hf&, pgv::ValidationMsg*)>(::COVESA::HUB_HF::Validate));


} // namespace validate
} // namespace pgv


namespace COVESA {
namespace HUB_HF {


// Validate checks the field values on ::COVESA::HUB_HF::Hub_hf with the rules
// defined in the proto definition for this message. If any rules are
// violated, the return value is false and an error message is written to the
// input string argument.

	

	

	

	

        

	

	

	



bool Validate(const ::COVESA::HUB_HF::Hub_hf& m, pgv::ValidationMsg* err) {
	(void)m;
	(void)err;
			if (m.has_truck()) {
				
	
	
	

	
	{
		pgv::ValidationMsg inner_err;
		if (m.has_truck() && !pgv::BaseValidator::AbstractCheckMessage(m.truck(), &inner_err)) {
			{
std::ostringstream msg("invalid ");
msg << "Hub_hfValidationError" << "." << "Truck";
msg << ": " << "embedded message failed validation";
msg << " | caused by " << inner_err;
*err = msg.str();
return false;
}
		}
	}
	

			}
		
		
	return true;
}


} // namespace
} // namespace

