#include <V2XHO_Node_Registration_Request_Include.h>

#define REGISTRATION_PACKET_LEGNTH 1024

#define REGISTRATION_ADDRESS "224.0.0.1"
#define REGISTRATION_PORT 434
#define REGISTRATION_PREFERENCE_LEVEL 1
#define MAX_REGISTRATION_INTERVAL 600
#define MIN_REGISTRATION_INTERVAL 0.75 * MAX_REGISTRATION_INTERVAL
#define REGISTRATION_LIFETIME 3 * MIN_REGISTRATION_INTERVAL 
#define MAX_REGISTRATION_LIFETIME 9000