// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ivdct/diag/fuel/fuel.proto
// Protobuf C++ Version: 6.31.1

#ifndef ivdct_2fdiag_2ffuel_2ffuel_2eproto_2epb_2eh
#define ivdct_2fdiag_2ffuel_2ffuel_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "validate/validate.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ivdct_2fdiag_2ffuel_2ffuel_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ivdct_2fdiag_2ffuel_2ffuel_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ivdct_2fdiag_2ffuel_2ffuel_2eproto;
}  // extern "C"
namespace IVDCT {
namespace DIAG {
namespace FUEL {
class Fuel;
struct FuelDefaultTypeInternal;
extern FuelDefaultTypeInternal _Fuel_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Fuel_class_data_;
}  // namespace FUEL
}  // namespace DIAG
}  // namespace IVDCT
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace IVDCT {
namespace DIAG {
namespace FUEL {

// ===================================================================


// -------------------------------------------------------------------

class Fuel final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:IVDCT.DIAG.FUEL.Fuel) */ {
 public:
  inline Fuel() : Fuel(nullptr) {}
  ~Fuel() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Fuel* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Fuel));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Fuel(::google::protobuf::internal::ConstantInitialized);

  inline Fuel(const Fuel& from) : Fuel(nullptr, from) {}
  inline Fuel(Fuel&& from) noexcept
      : Fuel(nullptr, ::std::move(from)) {}
  inline Fuel& operator=(const Fuel& from) {
    CopyFrom(from);
    return *this;
  }
  inline Fuel& operator=(Fuel&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Fuel& default_instance() {
    return *reinterpret_cast<const Fuel*>(
        &_Fuel_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Fuel& a, Fuel& b) { a.Swap(&b); }
  inline void Swap(Fuel* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Fuel* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Fuel* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Fuel>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Fuel& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Fuel& from) { Fuel::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Fuel* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "IVDCT.DIAG.FUEL.Fuel"; }

 protected:
  explicit Fuel(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Fuel(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Fuel& from);
  Fuel(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Fuel&& from) noexcept
      : Fuel(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEconomyCtFieldNumber = 1,
    kEconomyFieldNumber = 2,
  };
  // optional uint64 economy_ct = 1 [(.validate.rules) = {
  bool has_economy_ct() const;
  void clear_economy_ct() ;
  ::uint64_t economy_ct() const;
  void set_economy_ct(::uint64_t value);

  private:
  ::uint64_t _internal_economy_ct() const;
  void _internal_set_economy_ct(::uint64_t value);

  public:
  // optional uint32 economy = 2 [(.validate.rules) = {
  bool has_economy() const;
  void clear_economy() ;
  ::uint32_t economy() const;
  void set_economy(::uint32_t value);

  private:
  ::uint32_t _internal_economy() const;
  void _internal_set_economy(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:IVDCT.DIAG.FUEL.Fuel)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Fuel& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t economy_ct_;
    ::uint32_t economy_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ivdct_2fdiag_2ffuel_2ffuel_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Fuel_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Fuel

// optional uint64 economy_ct = 1 [(.validate.rules) = {
inline bool Fuel::has_economy_ct() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Fuel::clear_economy_ct() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.economy_ct_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::uint64_t Fuel::economy_ct() const {
  // @@protoc_insertion_point(field_get:IVDCT.DIAG.FUEL.Fuel.economy_ct)
  return _internal_economy_ct();
}
inline void Fuel::set_economy_ct(::uint64_t value) {
  _internal_set_economy_ct(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:IVDCT.DIAG.FUEL.Fuel.economy_ct)
}
inline ::uint64_t Fuel::_internal_economy_ct() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.economy_ct_;
}
inline void Fuel::_internal_set_economy_ct(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.economy_ct_ = value;
}

// optional uint32 economy = 2 [(.validate.rules) = {
inline bool Fuel::has_economy() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Fuel::clear_economy() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.economy_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::uint32_t Fuel::economy() const {
  // @@protoc_insertion_point(field_get:IVDCT.DIAG.FUEL.Fuel.economy)
  return _internal_economy();
}
inline void Fuel::set_economy(::uint32_t value) {
  _internal_set_economy(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:IVDCT.DIAG.FUEL.Fuel.economy)
}
inline ::uint32_t Fuel::_internal_economy() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.economy_;
}
inline void Fuel::_internal_set_economy(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.economy_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace FUEL
}  // namespace DIAG
}  // namespace IVDCT


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ivdct_2fdiag_2ffuel_2ffuel_2eproto_2epb_2eh
