// Code generated by protoc-gen-validate
// source: ads_hf/control/control.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "ads_hf/control/control.pb.h"


namespace ADS_HF {
namespace CONTROL {

using std::string;


extern bool Validate(const ::ADS_HF::CONTROL::Control& m, pgv::ValidationMsg* err);


} // namespace
} // namespace


#define X_ADS_HF_CONTROL_CONTROL(X) \
X(::ADS_HF::CONTROL::Control) \

