#include <V2XHO_Agent_Advertisements_Include.h>

#define ADVERTISEMENT_PACKET_LEGNTH 1024

#define ADVERTISEMENT_ADDRESS "224.0.0.1"
#define ADVERTISEMENT_PORT 434
#define ADVERTISEMENT_PREFERENCE_LEVEL 1
#define MAX_ADVERTISEMENT_INTERVAL 600
#define MIN_ADVERTISEMENT_INTERVAL 0.75 * MAX_ADVERTISEMENT_INTERVAL
#define ADVERTISEMENT_LIFETIME 3 * MIN_ADVERTISEMENT_INTERVAL 
#define MAX_ADVERTISEMENT_LIFETIME 9000

#define ADVERTISING_DEFAULT true

#define DEFAULT_RESTRATION_LIFETIME 60
