// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: covesa/ivdct/truck/adas/adas.proto
// Protobuf C++ Version: 6.31.1

#include "covesa/ivdct/truck/adas/adas.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace ADAS {

inline constexpr Adas::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : abs_{},
        tcs_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Adas::Adas(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Adas_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AdasDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AdasDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AdasDefaultTypeInternal() {}
  union {
    Adas _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AdasDefaultTypeInternal _Adas_default_instance_;
}  // namespace ADAS
}  // namespace TRUCK
}  // namespace IVDCT
}  // namespace COVESA
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto = nullptr;
const ::uint32_t
    TableStruct_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        PROTOBUF_FIELD_OFFSET(::COVESA::IVDCT::TRUCK::ADAS::Adas, _impl_.abs_),
        PROTOBUF_FIELD_OFFSET(::COVESA::IVDCT::TRUCK::ADAS::Adas, _impl_.tcs_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::COVESA::IVDCT::TRUCK::ADAS::Adas)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::COVESA::IVDCT::TRUCK::ADAS::_Adas_default_instance_._instance,
};
const char descriptor_table_protodef_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\"covesa/ivdct/truck/adas/adas.proto\022\027CO"
    "VESA.IVDCT.TRUCK.ADAS\032%covesa/ivdct/truc"
    "k/adas/abs/abs.proto\032%covesa/ivdct/truck"
    "/adas/tcs/tcs.proto\"d\n\004Adas\022-\n\003abs\030\001 \003(\013"
    "2 .COVESA.IVDCT.TRUCK.ADAS.ABS.Abs\022-\n\003tc"
    "s\030\002 \003(\0132 .COVESA.IVDCT.TRUCK.ADAS.TCS.Tc"
    "sb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto_deps[2] = {
        &::descriptor_table_covesa_2fivdct_2ftruck_2fadas_2fabs_2fabs_2eproto,
        &::descriptor_table_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto,
};
static ::absl::once_flag descriptor_table_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto = {
    false,
    false,
    249,
    descriptor_table_protodef_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto,
    "covesa/ivdct/truck/adas/adas.proto",
    &descriptor_table_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto_once,
    descriptor_table_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto_deps,
    2,
    1,
    schemas,
    file_default_instances,
    TableStruct_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto::offsets,
    file_level_enum_descriptors_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto,
    file_level_service_descriptors_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto,
};
namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace ADAS {
// ===================================================================

class Adas::_Internal {
 public:
};

void Adas::clear_abs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.abs_.Clear();
}
void Adas::clear_tcs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tcs_.Clear();
}
Adas::Adas(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Adas_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:COVESA.IVDCT.TRUCK.ADAS.Adas)
}
PROTOBUF_NDEBUG_INLINE Adas::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::COVESA::IVDCT::TRUCK::ADAS::Adas& from_msg)
      : abs_{visibility, arena, from.abs_},
        tcs_{visibility, arena, from.tcs_},
        _cached_size_{0} {}

Adas::Adas(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Adas& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Adas_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Adas* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:COVESA.IVDCT.TRUCK.ADAS.Adas)
}
PROTOBUF_NDEBUG_INLINE Adas::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : abs_{visibility, arena},
        tcs_{visibility, arena},
        _cached_size_{0} {}

inline void Adas::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Adas::~Adas() {
  // @@protoc_insertion_point(destructor:COVESA.IVDCT.TRUCK.ADAS.Adas)
  SharedDtor(*this);
}
inline void Adas::SharedDtor(MessageLite& self) {
  Adas& this_ = static_cast<Adas&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Adas::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Adas(arena);
}
constexpr auto Adas::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(Adas, _impl_.abs_) +
          decltype(Adas::_impl_.abs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(Adas, _impl_.tcs_) +
          decltype(Adas::_impl_.tcs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(Adas), alignof(Adas), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&Adas::PlacementNew_,
                                 sizeof(Adas),
                                 alignof(Adas));
  }
}
constexpr auto Adas::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Adas_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Adas::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Adas>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Adas::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Adas>(), &Adas::ByteSizeLong,
              &Adas::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Adas, _impl_._cached_size_),
          false,
      },
      &Adas::kDescriptorMethods,
      &descriptor_table_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Adas_class_data_ =
        Adas::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Adas::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Adas_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Adas_class_data_.tc_table);
  return Adas_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
Adas::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Adas_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::COVESA::IVDCT::TRUCK::ADAS::Adas>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs tcs = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 1, PROTOBUF_FIELD_OFFSET(Adas, _impl_.tcs_)}},
    // repeated .COVESA.IVDCT.TRUCK.ADAS.ABS.Abs abs = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Adas, _impl_.abs_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .COVESA.IVDCT.TRUCK.ADAS.ABS.Abs abs = 1;
    {PROTOBUF_FIELD_OFFSET(Adas, _impl_.abs_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs tcs = 2;
    {PROTOBUF_FIELD_OFFSET(Adas, _impl_.tcs_), 0, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::COVESA::IVDCT::TRUCK::ADAS::ABS::Abs>()},
      {::_pbi::TcParser::GetTable<::COVESA::IVDCT::TRUCK::ADAS::TCS::Tcs>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Adas::Clear() {
// @@protoc_insertion_point(message_clear_start:COVESA.IVDCT.TRUCK.ADAS.Adas)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.abs_.Clear();
  _impl_.tcs_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Adas::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Adas& this_ = static_cast<const Adas&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Adas::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Adas& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:COVESA.IVDCT.TRUCK.ADAS.Adas)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .COVESA.IVDCT.TRUCK.ADAS.ABS.Abs abs = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_abs_size());
       i < n; i++) {
    const auto& repfield = this_._internal_abs().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  // repeated .COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs tcs = 2;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this_._internal_tcs_size());
       i < n; i++) {
    const auto& repfield = this_._internal_tcs().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            2, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:COVESA.IVDCT.TRUCK.ADAS.Adas)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Adas::ByteSizeLong(const MessageLite& base) {
  const Adas& this_ = static_cast<const Adas&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Adas::ByteSizeLong() const {
  const Adas& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:COVESA.IVDCT.TRUCK.ADAS.Adas)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .COVESA.IVDCT.TRUCK.ADAS.ABS.Abs abs = 1;
    {
      total_size += 1UL * this_._internal_abs_size();
      for (const auto& msg : this_._internal_abs()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs tcs = 2;
    {
      total_size += 1UL * this_._internal_tcs_size();
      for (const auto& msg : this_._internal_tcs()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Adas::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Adas*>(&to_msg);
  auto& from = static_cast<const Adas&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:COVESA.IVDCT.TRUCK.ADAS.Adas)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_abs()->MergeFrom(
      from._internal_abs());
  _this->_internal_mutable_tcs()->MergeFrom(
      from._internal_tcs());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Adas::CopyFrom(const Adas& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:COVESA.IVDCT.TRUCK.ADAS.Adas)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Adas::InternalSwap(Adas* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.abs_.InternalSwap(&other->_impl_.abs_);
  _impl_.tcs_.InternalSwap(&other->_impl_.tcs_);
}

::google::protobuf::Metadata Adas::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace ADAS
}  // namespace TRUCK
}  // namespace IVDCT
}  // namespace COVESA
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_covesa_2fivdct_2ftruck_2fadas_2fadas_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
