// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtg/driver/driver.proto
// Protobuf C++ Version: 6.31.1

#ifndef dtg_2fdriver_2fdriver_2eproto_2epb_2eh
#define dtg_2fdriver_2fdriver_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "validate/validate.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_dtg_2fdriver_2fdriver_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_dtg_2fdriver_2fdriver_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_dtg_2fdriver_2fdriver_2eproto;
}  // extern "C"
namespace DTG {
namespace DRIVER {
class Driver;
struct DriverDefaultTypeInternal;
extern DriverDefaultTypeInternal _Driver_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Driver_class_data_;
}  // namespace DRIVER
}  // namespace DTG
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace DTG {
namespace DRIVER {

// ===================================================================


// -------------------------------------------------------------------

class Driver final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DTG.DRIVER.Driver) */ {
 public:
  inline Driver() : Driver(nullptr) {}
  ~Driver() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Driver* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Driver));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Driver(::google::protobuf::internal::ConstantInitialized);

  inline Driver(const Driver& from) : Driver(nullptr, from) {}
  inline Driver(Driver&& from) noexcept
      : Driver(nullptr, ::std::move(from)) {}
  inline Driver& operator=(const Driver& from) {
    CopyFrom(from);
    return *this;
  }
  inline Driver& operator=(Driver&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Driver& default_instance() {
    return *reinterpret_cast<const Driver*>(
        &_Driver_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Driver& a, Driver& b) { a.Swap(&b); }
  inline void Swap(Driver* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Driver* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Driver* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Driver>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Driver& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Driver& from) { Driver::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Driver* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "DTG.DRIVER.Driver"; }

 protected:
  explicit Driver(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Driver(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Driver& from);
  Driver(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Driver&& from) noexcept
      : Driver(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBusinessNumberFieldNumber = 1,
    kDriverCodeFieldNumber = 2,
  };
  // optional string business_number = 1 [(.validate.rules) = {
  bool has_business_number() const;
  void clear_business_number() ;
  const ::std::string& business_number() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_business_number(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_business_number();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_business_number();
  void set_allocated_business_number(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_business_number() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_business_number(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_business_number();

  public:
  // optional string driver_code = 2 [(.validate.rules) = {
  bool has_driver_code() const;
  void clear_driver_code() ;
  const ::std::string& driver_code() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_driver_code(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_driver_code();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_driver_code();
  void set_allocated_driver_code(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_driver_code() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_driver_code(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_driver_code();

  public:
  // @@protoc_insertion_point(class_scope:DTG.DRIVER.Driver)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 52,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Driver& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr business_number_;
    ::google::protobuf::internal::ArenaStringPtr driver_code_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dtg_2fdriver_2fdriver_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Driver_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Driver

// optional string business_number = 1 [(.validate.rules) = {
inline bool Driver::has_business_number() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Driver::clear_business_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.business_number_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& Driver::business_number() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DTG.DRIVER.Driver.business_number)
  return _internal_business_number();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Driver::set_business_number(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.business_number_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DTG.DRIVER.Driver.business_number)
}
inline ::std::string* PROTOBUF_NONNULL Driver::mutable_business_number()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_business_number();
  // @@protoc_insertion_point(field_mutable:DTG.DRIVER.Driver.business_number)
  return _s;
}
inline const ::std::string& Driver::_internal_business_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.business_number_.Get();
}
inline void Driver::_internal_set_business_number(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.business_number_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Driver::_internal_mutable_business_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.business_number_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Driver::release_business_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:DTG.DRIVER.Driver.business_number)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.business_number_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.business_number_.Set("", GetArena());
  }
  return released;
}
inline void Driver::set_allocated_business_number(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.business_number_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.business_number_.IsDefault()) {
    _impl_.business_number_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:DTG.DRIVER.Driver.business_number)
}

// optional string driver_code = 2 [(.validate.rules) = {
inline bool Driver::has_driver_code() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Driver::clear_driver_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.driver_code_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& Driver::driver_code() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DTG.DRIVER.Driver.driver_code)
  return _internal_driver_code();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Driver::set_driver_code(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.driver_code_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DTG.DRIVER.Driver.driver_code)
}
inline ::std::string* PROTOBUF_NONNULL Driver::mutable_driver_code()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_driver_code();
  // @@protoc_insertion_point(field_mutable:DTG.DRIVER.Driver.driver_code)
  return _s;
}
inline const ::std::string& Driver::_internal_driver_code() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.driver_code_.Get();
}
inline void Driver::_internal_set_driver_code(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.driver_code_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Driver::_internal_mutable_driver_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.driver_code_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Driver::release_driver_code() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:DTG.DRIVER.Driver.driver_code)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.driver_code_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.driver_code_.Set("", GetArena());
  }
  return released;
}
inline void Driver::set_allocated_driver_code(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.driver_code_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.driver_code_.IsDefault()) {
    _impl_.driver_code_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:DTG.DRIVER.Driver.driver_code)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace DRIVER
}  // namespace DTG


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // dtg_2fdriver_2fdriver_2eproto_2epb_2eh
