// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ads_hf/decision/cipo/cipo.proto
// Protobuf C++ Version: 6.31.1

#include "ads_hf/decision/cipo/cipo.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ADS_HF {
namespace DECISION {
namespace CIPO {

inline constexpr Cipo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        present_{static_cast< ::ADS_HF::DECISION::CIPO::Cipo_Present >(0)},
        dist_{0},
        speed_{0u},
        predict_{static_cast< ::ADS_HF::DECISION::CIPO::Cipo_Predict >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR Cipo::Cipo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Cipo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CipoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CipoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CipoDefaultTypeInternal() {}
  union {
    Cipo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CipoDefaultTypeInternal _Cipo_default_instance_;
}  // namespace CIPO
}  // namespace DECISION
}  // namespace ADS_HF
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto = nullptr;
const ::uint32_t
    TableStruct_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::ADS_HF::DECISION::CIPO::Cipo, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::ADS_HF::DECISION::CIPO::Cipo, _impl_.present_),
        PROTOBUF_FIELD_OFFSET(::ADS_HF::DECISION::CIPO::Cipo, _impl_.dist_),
        PROTOBUF_FIELD_OFFSET(::ADS_HF::DECISION::CIPO::Cipo, _impl_.speed_),
        PROTOBUF_FIELD_OFFSET(::ADS_HF::DECISION::CIPO::Cipo, _impl_.predict_),
        0,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::ADS_HF::DECISION::CIPO::Cipo)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::ADS_HF::DECISION::CIPO::_Cipo_default_instance_._instance,
};
const char descriptor_table_protodef_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\037ads_hf/decision/cipo/cipo.proto\022\024ADS_H"
    "F.DECISION.CIPO\032\027validate/validate.proto"
    "\"\211\003\n\004Cipo\022B\n\007present\030\001 \001(\0162\".ADS_HF.DECI"
    "SION.CIPO.Cipo.PresentB\010\372B\005\202\001\002\020\001H\000\210\001\001\022\'\n"
    "\004dist\030\002 \001(\005B\024\372B\021\032\017\030\377\377\001(\201\200\376\377\377\377\377\377\377\001H\001\210\001\001\022\036"
    "\n\005speed\030\003 \001(\rB\n\372B\007*\005\030\377\?(\000H\002\210\001\001\022B\n\007predic"
    "t\030\004 \001(\0162\".ADS_HF.DECISION.CIPO.Cipo.Pred"
    "ictB\010\372B\005\202\001\002\020\001H\003\210\001\001\"2\n\007Present\022\025\n\021CIPO_PR"
    "ESENT_NONE\020\000\022\020\n\014CIPO_PRESENT\020\001\"Q\n\007Predic"
    "t\022\025\n\021CIPO_PREDICT_NONE\020\000\022\026\n\022CIPO_PREDICT"
    "_CUTIN\020\001\022\027\n\023CIPO_PREDICT_CUTOUT\020\002B\n\n\010_pr"
    "esentB\007\n\005_distB\010\n\006_speedB\n\n\010_predictb\006pr"
    "oto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto_deps[1] = {
        &::descriptor_table_validate_2fvalidate_2eproto,
};
static ::absl::once_flag descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto = {
    false,
    false,
    484,
    descriptor_table_protodef_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto,
    "ads_hf/decision/cipo/cipo.proto",
    &descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto_once,
    descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto::offsets,
    file_level_enum_descriptors_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto,
    file_level_service_descriptors_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto,
};
namespace ADS_HF {
namespace DECISION {
namespace CIPO {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Cipo_Present_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto);
  return file_level_enum_descriptors_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Cipo_Present_internal_data_[] = {
    131072u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Cipo_Predict_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto);
  return file_level_enum_descriptors_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Cipo_Predict_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class Cipo::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Cipo>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Cipo, _impl_._has_bits_);
};

Cipo::Cipo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Cipo_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ADS_HF.DECISION.CIPO.Cipo)
}
Cipo::Cipo(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Cipo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Cipo_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Cipo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Cipo::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, present_),
           0,
           offsetof(Impl_, predict_) -
               offsetof(Impl_, present_) +
               sizeof(Impl_::predict_));
}
Cipo::~Cipo() {
  // @@protoc_insertion_point(destructor:ADS_HF.DECISION.CIPO.Cipo)
  SharedDtor(*this);
}
inline void Cipo::SharedDtor(MessageLite& self) {
  Cipo& this_ = static_cast<Cipo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Cipo::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Cipo(arena);
}
constexpr auto Cipo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Cipo),
                                            alignof(Cipo));
}
constexpr auto Cipo::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Cipo_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Cipo::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Cipo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Cipo::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Cipo>(), &Cipo::ByteSizeLong,
              &Cipo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Cipo, _impl_._cached_size_),
          false,
      },
      &Cipo::kDescriptorMethods,
      &descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Cipo_class_data_ =
        Cipo::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Cipo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Cipo_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Cipo_class_data_.tc_table);
  return Cipo_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
Cipo::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Cipo, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Cipo_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ADS_HF::DECISION::CIPO::Cipo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .ADS_HF.DECISION.CIPO.Cipo.Predict predict = 4 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Cipo, _impl_.predict_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(Cipo, _impl_.predict_)}},
    // optional .ADS_HF.DECISION.CIPO.Cipo.Present present = 1 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Cipo, _impl_.present_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Cipo, _impl_.present_)}},
    // optional int32 dist = 2 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Cipo, _impl_.dist_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Cipo, _impl_.dist_)}},
    // optional uint32 speed = 3 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Cipo, _impl_.speed_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Cipo, _impl_.speed_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .ADS_HF.DECISION.CIPO.Cipo.Present present = 1 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(Cipo, _impl_.present_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional int32 dist = 2 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(Cipo, _impl_.dist_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint32 speed = 3 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(Cipo, _impl_.speed_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional .ADS_HF.DECISION.CIPO.Cipo.Predict predict = 4 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(Cipo, _impl_.predict_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Cipo::Clear() {
// @@protoc_insertion_point(message_clear_start:ADS_HF.DECISION.CIPO.Cipo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    ::memset(&_impl_.present_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.predict_) -
        reinterpret_cast<char*>(&_impl_.present_)) + sizeof(_impl_.predict_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Cipo::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Cipo& this_ = static_cast<const Cipo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Cipo::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Cipo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:ADS_HF.DECISION.CIPO.Cipo)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .ADS_HF.DECISION.CIPO.Cipo.Present present = 1 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_present(), target);
  }

  // optional int32 dist = 2 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000002u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_dist(), target);
  }

  // optional uint32 speed = 3 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_speed(), target);
  }

  // optional .ADS_HF.DECISION.CIPO.Cipo.Predict predict = 4 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000008u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        4, this_._internal_predict(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ADS_HF.DECISION.CIPO.Cipo)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Cipo::ByteSizeLong(const MessageLite& base) {
  const Cipo& this_ = static_cast<const Cipo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Cipo::ByteSizeLong() const {
  const Cipo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:ADS_HF.DECISION.CIPO.Cipo)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    // optional .ADS_HF.DECISION.CIPO.Cipo.Present present = 1 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_present());
    }
    // optional int32 dist = 2 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_dist());
    }
    // optional uint32 speed = 3 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_speed());
    }
    // optional .ADS_HF.DECISION.CIPO.Cipo.Predict predict = 4 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_predict());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Cipo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Cipo*>(&to_msg);
  auto& from = static_cast<const Cipo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ADS_HF.DECISION.CIPO.Cipo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.present_ = from._impl_.present_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.dist_ = from._impl_.dist_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.speed_ = from._impl_.speed_;
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _this->_impl_.predict_ = from._impl_.predict_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Cipo::CopyFrom(const Cipo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ADS_HF.DECISION.CIPO.Cipo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Cipo::InternalSwap(Cipo* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Cipo, _impl_.predict_)
      + sizeof(Cipo::_impl_.predict_)
      - PROTOBUF_FIELD_OFFSET(Cipo, _impl_.present_)>(
          reinterpret_cast<char*>(&_impl_.present_),
          reinterpret_cast<char*>(&other->_impl_.present_));
}

::google::protobuf::Metadata Cipo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace CIPO
}  // namespace DECISION
}  // namespace ADS_HF
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_ads_5fhf_2fdecision_2fcipo_2fcipo_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
