// Code generated by protoc-gen-validate
// source: ivdct/weight/axle_weight/axle_weight.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "ivdct/weight/axle_weight/axle_weight.pb.h"


namespace IVDCT {
namespace WEIGHT {
namespace AXLE_WEIGHT {

using std::string;


extern bool Validate(const ::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight& m, pgv::ValidationMsg* err);


} // namespace
} // namespace
} // namespace


#define X_IVDCT_WEIGHT_AXLE_WEIGHT_AXLE_WEIGHT(X) \
X(::IVDCT::WEIGHT::AXLE_WEIGHT::Axle_weight) \

