// Code generated by protoc-gen-validate
// source: covesa/ivdct/truck/powertrain/powertrain.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "covesa/ivdct/truck/powertrain/powertrain.pb.h"


namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace POWERTRAIN {

using std::string;


extern bool Validate(const ::COVESA::IVDCT::TRUCK::POWERTRAIN::Powertrain& m, pgv::ValidationMsg* err);


} // namespace
} // namespace
} // namespace
} // namespace


#define X_COVESA_IVDCT_TRUCK_POWERTRAIN_POWERTRAIN(X) \
X(::COVESA::IVDCT::TRUCK::POWERTRAIN::Powertrain) \

