// Code generated by protoc-gen-validate
// source: covesa/hub_hf/truck/vehicle/currentlocation/currentlocation.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "covesa/hub_hf/truck/vehicle/currentlocation/currentlocation.pb.h"


namespace COVESA {
namespace HUB_HF {
namespace TRUCK {
namespace VEHICLE {
namespace CURRENTLOCATION {

using std::string;


extern bool Validate(const ::COVESA::HUB_HF::TRUCK::VEHICLE::CURRENTLOCATION::Currentlocation& m, pgv::ValidationMsg* err);


} // namespace
} // namespace
} // namespace
} // namespace
} // namespace


#define X_COVESA_HUB_HF_TRUCK_VEHICLE_CURRENTLOCATION_CURRENTLOCATION(X) \
X(::COVESA::HUB_HF::TRUCK::VEHICLE::CURRENTLOCATION::Currentlocation) \

