// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: visa/testmessage00/infrasafetymsg/infrasafetymsg.proto
// Protobuf C++ Version: 6.31.1

#include "visa/testmessage00/infrasafetymsg/infrasafetymsg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace VISA {
namespace TestMessage00 {
namespace InfraSafetyMsg {

inline constexpr InfraSafetyMsg_positionR::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        latitude_{0},
        longitude_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InfraSafetyMsg_positionR::InfraSafetyMsg_positionR(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(InfraSafetyMsg_positionR_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InfraSafetyMsg_positionRDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InfraSafetyMsg_positionRDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InfraSafetyMsg_positionRDefaultTypeInternal() {}
  union {
    InfraSafetyMsg_positionR _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InfraSafetyMsg_positionRDefaultTypeInternal _InfraSafetyMsg_positionR_default_instance_;

inline constexpr InfraSafetyMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        position_{nullptr},
        rsuid_{0u},
        sequencenumber_{0u},
        cpuload_{0},
        memload_{0},
        centertimestamp_{::uint64_t{0u}},
        rsutransmittedtimestamp_{::uint64_t{0u}},
        v2xreceivedtimestamp_{::uint64_t{0u}},
        rsutemperature_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR InfraSafetyMsg::InfraSafetyMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(InfraSafetyMsg_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct InfraSafetyMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InfraSafetyMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InfraSafetyMsgDefaultTypeInternal() {}
  union {
    InfraSafetyMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InfraSafetyMsgDefaultTypeInternal _InfraSafetyMsg_default_instance_;
}  // namespace InfraSafetyMsg
}  // namespace TestMessage00
}  // namespace VISA
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto = nullptr;
const ::uint32_t
    TableStruct_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg_positionR, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg_positionR, _impl_.latitude_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg_positionR, _impl_.longitude_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_._has_bits_),
        12, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.rsuid_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.sequencenumber_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.position_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.cpuload_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.memload_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.rsutemperature_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.centertimestamp_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.rsutransmittedtimestamp_),
        PROTOBUF_FIELD_OFFSET(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg, _impl_.v2xreceivedtimestamp_),
        1,
        2,
        0,
        3,
        4,
        8,
        5,
        6,
        7,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg_positionR)},
        {7, sizeof(::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::VISA::TestMessage00::InfraSafetyMsg::_InfraSafetyMsg_positionR_default_instance_._instance,
    &::VISA::TestMessage00::InfraSafetyMsg::_InfraSafetyMsg_default_instance_._instance,
};
const char descriptor_table_protodef_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n6visa/testmessage00/infrasafetymsg/infr"
    "asafetymsg.proto\022!VISA.TestMessage00.Inf"
    "raSafetyMsg\032\036google/protobuf/wrappers.pr"
    "oto\032\027validate/validate.proto\"\343\005\n\016InfraSa"
    "fetyMsg\022!\n\005rsuid\030\001 \001(\rB\r\372B\n*\010\030\377\377\377\377\017(\000H\000\210"
    "\001\001\022&\n\016sequencenumber\030\002 \001(\rB\t\372B\006*\004\030\177(\000H\001\210"
    "\001\001\022R\n\010position\030\003 \001(\0132;.VISA.TestMessage0"
    "0.InfraSafetyMsg.InfraSafetyMsg.position"
    "RH\002\210\001\001\022\037\n\007cpuload\030\004 \001(\005B\t\372B\006\032\004\030e(\000H\003\210\001\001\022"
    "\037\n\007memload\030\005 \001(\005B\t\372B\006\032\004\030e(\000H\004\210\001\001\022\'\n\016rsut"
    "emperature\030\006 \001(\rB\n\372B\007*\005\030\277\001(\000H\005\210\001\001\0220\n\017cen"
    "tertimestamp\030\007 \001(\004B\022\372B\0172\r\030\377\377\377\377\377\377\377\377\377\001(\000H\006"
    "\210\001\001\0228\n\027rsutransmittedtimestamp\030\010 \001(\004B\022\372B"
    "\0172\r\030\377\377\377\377\377\377\377\377\377\001(\000H\007\210\001\001\0225\n\024v2xreceivedtime"
    "stamp\030\t \001(\004B\022\372B\0172\r\030\377\377\377\377\377\377\377\377\377\001(\000H\010\210\001\001\032\205\001\n"
    "\tpositionR\022-\n\010latitude\030\001 \001(\005B\026\372B\023\032\021\030\201\322\223\255"
    "\003(\200\256\354\322\374\377\377\377\377\001H\000\210\001\001\022.\n\tlongitude\030\002 \001(\005B\026\372B"
    "\023\032\021\030\201\244\247\332\006(\201\334\330\245\371\377\377\377\377\001H\001\210\001\001B\013\n\t_latitudeB\014"
    "\n\n_longitudeB\010\n\006_rsuidB\021\n\017_sequencenumbe"
    "rB\013\n\t_positionB\n\n\010_cpuloadB\n\n\010_memloadB\021"
    "\n\017_rsutemperatureB\022\n\020_centertimestampB\032\n"
    "\030_rsutransmittedtimestampB\027\n\025_v2xreceive"
    "dtimestampb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto_deps[2] = {
        &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
        &::descriptor_table_validate_2fvalidate_2eproto,
};
static ::absl::once_flag descriptor_table_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto = {
    false,
    false,
    898,
    descriptor_table_protodef_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto,
    "visa/testmessage00/infrasafetymsg/infrasafetymsg.proto",
    &descriptor_table_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto_once,
    descriptor_table_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto_deps,
    2,
    2,
    schemas,
    file_default_instances,
    TableStruct_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto::offsets,
    file_level_enum_descriptors_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto,
    file_level_service_descriptors_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto,
};
namespace VISA {
namespace TestMessage00 {
namespace InfraSafetyMsg {
// ===================================================================

class InfraSafetyMsg_positionR::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<InfraSafetyMsg_positionR>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_._has_bits_);
};

InfraSafetyMsg_positionR::InfraSafetyMsg_positionR(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InfraSafetyMsg_positionR_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR)
}
InfraSafetyMsg_positionR::InfraSafetyMsg_positionR(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const InfraSafetyMsg_positionR& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InfraSafetyMsg_positionR_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE InfraSafetyMsg_positionR::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void InfraSafetyMsg_positionR::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, latitude_),
           0,
           offsetof(Impl_, longitude_) -
               offsetof(Impl_, latitude_) +
               sizeof(Impl_::longitude_));
}
InfraSafetyMsg_positionR::~InfraSafetyMsg_positionR() {
  // @@protoc_insertion_point(destructor:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR)
  SharedDtor(*this);
}
inline void InfraSafetyMsg_positionR::SharedDtor(MessageLite& self) {
  InfraSafetyMsg_positionR& this_ = static_cast<InfraSafetyMsg_positionR&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL InfraSafetyMsg_positionR::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) InfraSafetyMsg_positionR(arena);
}
constexpr auto InfraSafetyMsg_positionR::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(InfraSafetyMsg_positionR),
                                            alignof(InfraSafetyMsg_positionR));
}
constexpr auto InfraSafetyMsg_positionR::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_InfraSafetyMsg_positionR_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &InfraSafetyMsg_positionR::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<InfraSafetyMsg_positionR>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &InfraSafetyMsg_positionR::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<InfraSafetyMsg_positionR>(), &InfraSafetyMsg_positionR::ByteSizeLong,
              &InfraSafetyMsg_positionR::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_._cached_size_),
          false,
      },
      &InfraSafetyMsg_positionR::kDescriptorMethods,
      &descriptor_table_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull InfraSafetyMsg_positionR_class_data_ =
        InfraSafetyMsg_positionR::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
InfraSafetyMsg_positionR::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&InfraSafetyMsg_positionR_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(InfraSafetyMsg_positionR_class_data_.tc_table);
  return InfraSafetyMsg_positionR_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
InfraSafetyMsg_positionR::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    InfraSafetyMsg_positionR_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg_positionR>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional int32 longitude = 2 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InfraSafetyMsg_positionR, _impl_.longitude_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_.longitude_)}},
    // optional int32 latitude = 1 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InfraSafetyMsg_positionR, _impl_.latitude_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_.latitude_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 latitude = 1 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_.latitude_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 longitude = 2 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_.longitude_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void InfraSafetyMsg_positionR::Clear() {
// @@protoc_insertion_point(message_clear_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.latitude_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.longitude_) -
        reinterpret_cast<char*>(&_impl_.latitude_)) + sizeof(_impl_.longitude_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL InfraSafetyMsg_positionR::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const InfraSafetyMsg_positionR& this_ = static_cast<const InfraSafetyMsg_positionR&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL InfraSafetyMsg_positionR::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const InfraSafetyMsg_positionR& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 latitude = 1 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000001u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_latitude(), target);
  }

  // optional int32 longitude = 2 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000002u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_longitude(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t InfraSafetyMsg_positionR::ByteSizeLong(const MessageLite& base) {
  const InfraSafetyMsg_positionR& this_ = static_cast<const InfraSafetyMsg_positionR&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t InfraSafetyMsg_positionR::ByteSizeLong() const {
  const InfraSafetyMsg_positionR& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // optional int32 latitude = 1 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_latitude());
    }
    // optional int32 longitude = 2 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_longitude());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void InfraSafetyMsg_positionR::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InfraSafetyMsg_positionR*>(&to_msg);
  auto& from = static_cast<const InfraSafetyMsg_positionR&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.latitude_ = from._impl_.latitude_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.longitude_ = from._impl_.longitude_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InfraSafetyMsg_positionR::CopyFrom(const InfraSafetyMsg_positionR& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InfraSafetyMsg_positionR::InternalSwap(InfraSafetyMsg_positionR* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_.longitude_)
      + sizeof(InfraSafetyMsg_positionR::_impl_.longitude_)
      - PROTOBUF_FIELD_OFFSET(InfraSafetyMsg_positionR, _impl_.latitude_)>(
          reinterpret_cast<char*>(&_impl_.latitude_),
          reinterpret_cast<char*>(&other->_impl_.latitude_));
}

::google::protobuf::Metadata InfraSafetyMsg_positionR::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class InfraSafetyMsg::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<InfraSafetyMsg>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_._has_bits_);
};

InfraSafetyMsg::InfraSafetyMsg(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InfraSafetyMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
}
PROTOBUF_NDEBUG_INLINE InfraSafetyMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

InfraSafetyMsg::InfraSafetyMsg(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const InfraSafetyMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, InfraSafetyMsg_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  InfraSafetyMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.position_ = ((cached_has_bits & 0x00000001u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.position_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, rsuid_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, rsuid_),
           offsetof(Impl_, rsutemperature_) -
               offsetof(Impl_, rsuid_) +
               sizeof(Impl_::rsutemperature_));

  // @@protoc_insertion_point(copy_constructor:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
}
PROTOBUF_NDEBUG_INLINE InfraSafetyMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void InfraSafetyMsg::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, position_),
           0,
           offsetof(Impl_, rsutemperature_) -
               offsetof(Impl_, position_) +
               sizeof(Impl_::rsutemperature_));
}
InfraSafetyMsg::~InfraSafetyMsg() {
  // @@protoc_insertion_point(destructor:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
  SharedDtor(*this);
}
inline void InfraSafetyMsg::SharedDtor(MessageLite& self) {
  InfraSafetyMsg& this_ = static_cast<InfraSafetyMsg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.position_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL InfraSafetyMsg::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) InfraSafetyMsg(arena);
}
constexpr auto InfraSafetyMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(InfraSafetyMsg),
                                            alignof(InfraSafetyMsg));
}
constexpr auto InfraSafetyMsg::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_InfraSafetyMsg_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &InfraSafetyMsg::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<InfraSafetyMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &InfraSafetyMsg::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<InfraSafetyMsg>(), &InfraSafetyMsg::ByteSizeLong,
              &InfraSafetyMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_._cached_size_),
          false,
      },
      &InfraSafetyMsg::kDescriptorMethods,
      &descriptor_table_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull InfraSafetyMsg_class_data_ =
        InfraSafetyMsg::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
InfraSafetyMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&InfraSafetyMsg_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(InfraSafetyMsg_class_data_.tc_table);
  return InfraSafetyMsg_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 1, 0, 2>
InfraSafetyMsg::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    InfraSafetyMsg_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional uint32 rsuid = 1 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InfraSafetyMsg, _impl_.rsuid_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.rsuid_)}},
    // optional uint32 sequencenumber = 2 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InfraSafetyMsg, _impl_.sequencenumber_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.sequencenumber_)}},
    // optional .VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR position = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.position_)}},
    // optional int32 cpuload = 4 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InfraSafetyMsg, _impl_.cpuload_), 3>(),
     {32, 3, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.cpuload_)}},
    // optional int32 memload = 5 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InfraSafetyMsg, _impl_.memload_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.memload_)}},
    // optional uint32 rsutemperature = 6 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(InfraSafetyMsg, _impl_.rsutemperature_), 8>(),
     {48, 8, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.rsutemperature_)}},
    // optional uint64 centertimestamp = 7 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(InfraSafetyMsg, _impl_.centertimestamp_), 5>(),
     {56, 5, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.centertimestamp_)}},
    // optional uint64 rsutransmittedtimestamp = 8 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(InfraSafetyMsg, _impl_.rsutransmittedtimestamp_), 6>(),
     {64, 6, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.rsutransmittedtimestamp_)}},
    // optional uint64 v2xreceivedtimestamp = 9 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(InfraSafetyMsg, _impl_.v2xreceivedtimestamp_), 7>(),
     {72, 7, 0, PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.v2xreceivedtimestamp_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint32 rsuid = 1 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.rsuid_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint32 sequencenumber = 2 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.sequencenumber_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional .VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR position = 3;
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.position_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional int32 cpuload = 4 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.cpuload_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 memload = 5 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.memload_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint32 rsutemperature = 6 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.rsutemperature_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional uint64 centertimestamp = 7 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.centertimestamp_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 rsutransmittedtimestamp = 8 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.rsutransmittedtimestamp_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 v2xreceivedtimestamp = 9 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.v2xreceivedtimestamp_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::VISA::TestMessage00::InfraSafetyMsg::InfraSafetyMsg_positionR>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void InfraSafetyMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    ABSL_DCHECK(_impl_.position_ != nullptr);
    _impl_.position_->Clear();
  }
  if ((cached_has_bits & 0x000000feu) != 0) {
    ::memset(&_impl_.rsuid_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.v2xreceivedtimestamp_) -
        reinterpret_cast<char*>(&_impl_.rsuid_)) + sizeof(_impl_.v2xreceivedtimestamp_));
  }
  _impl_.rsutemperature_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL InfraSafetyMsg::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const InfraSafetyMsg& this_ = static_cast<const InfraSafetyMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL InfraSafetyMsg::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const InfraSafetyMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint32 rsuid = 1 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_rsuid(), target);
  }

  // optional uint32 sequencenumber = 2 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this_._internal_sequencenumber(), target);
  }

  // optional .VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR position = 3;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.position_, this_._impl_.position_->GetCachedSize(), target,
        stream);
  }

  // optional int32 cpuload = 4 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000008u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
            stream, this_._internal_cpuload(), target);
  }

  // optional int32 memload = 5 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000010u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_memload(), target);
  }

  // optional uint32 rsutemperature = 6 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000100u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this_._internal_rsutemperature(), target);
  }

  // optional uint64 centertimestamp = 7 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000020u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        7, this_._internal_centertimestamp(), target);
  }

  // optional uint64 rsutransmittedtimestamp = 8 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000040u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        8, this_._internal_rsutransmittedtimestamp(), target);
  }

  // optional uint64 v2xreceivedtimestamp = 9 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000080u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        9, this_._internal_v2xreceivedtimestamp(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t InfraSafetyMsg::ByteSizeLong(const MessageLite& base) {
  const InfraSafetyMsg& this_ = static_cast<const InfraSafetyMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t InfraSafetyMsg::ByteSizeLong() const {
  const InfraSafetyMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    // optional .VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg.positionR position = 3;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.position_);
    }
    // optional uint32 rsuid = 1 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_rsuid());
    }
    // optional uint32 sequencenumber = 2 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_sequencenumber());
    }
    // optional int32 cpuload = 4 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_cpuload());
    }
    // optional int32 memload = 5 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000010u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_memload());
    }
    // optional uint64 centertimestamp = 7 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000020u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_centertimestamp());
    }
    // optional uint64 rsutransmittedtimestamp = 8 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000040u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_rsutransmittedtimestamp());
    }
    // optional uint64 v2xreceivedtimestamp = 9 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000080u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_v2xreceivedtimestamp());
    }
  }
   {
    // optional uint32 rsutemperature = 6 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000100u) != 0) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_rsutemperature());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void InfraSafetyMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<InfraSafetyMsg*>(&to_msg);
  auto& from = static_cast<const InfraSafetyMsg&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      ABSL_DCHECK(from._impl_.position_ != nullptr);
      if (_this->_impl_.position_ == nullptr) {
        _this->_impl_.position_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.position_);
      } else {
        _this->_impl_.position_->MergeFrom(*from._impl_.position_);
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.rsuid_ = from._impl_.rsuid_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.sequencenumber_ = from._impl_.sequencenumber_;
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _this->_impl_.cpuload_ = from._impl_.cpuload_;
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _this->_impl_.memload_ = from._impl_.memload_;
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      _this->_impl_.centertimestamp_ = from._impl_.centertimestamp_;
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      _this->_impl_.rsutransmittedtimestamp_ = from._impl_.rsutransmittedtimestamp_;
    }
    if ((cached_has_bits & 0x00000080u) != 0) {
      _this->_impl_.v2xreceivedtimestamp_ = from._impl_.v2xreceivedtimestamp_;
    }
  }
  if ((cached_has_bits & 0x00000100u) != 0) {
    _this->_impl_.rsutemperature_ = from._impl_.rsutemperature_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InfraSafetyMsg::CopyFrom(const InfraSafetyMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VISA.TestMessage00.InfraSafetyMsg.InfraSafetyMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void InfraSafetyMsg::InternalSwap(InfraSafetyMsg* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.rsutemperature_)
      + sizeof(InfraSafetyMsg::_impl_.rsutemperature_)
      - PROTOBUF_FIELD_OFFSET(InfraSafetyMsg, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::google::protobuf::Metadata InfraSafetyMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace InfraSafetyMsg
}  // namespace TestMessage00
}  // namespace VISA
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_visa_2ftestmessage00_2finfrasafetymsg_2finfrasafetymsg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
