// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: covesa/ivdct/truck/adas/tcs/tcs.proto
// Protobuf C++ Version: 6.31.1

#include "covesa/ivdct/truck/adas/tcs/tcs.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace ADAS {
namespace TCS {

inline constexpr Tcs::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        isenabled_{false},
        iserror_{false},
        isengaged_{false} {}

template <typename>
PROTOBUF_CONSTEXPR Tcs::Tcs(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Tcs_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TcsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TcsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TcsDefaultTypeInternal() {}
  union {
    Tcs _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TcsDefaultTypeInternal _Tcs_default_instance_;
}  // namespace TCS
}  // namespace ADAS
}  // namespace TRUCK
}  // namespace IVDCT
}  // namespace COVESA
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto = nullptr;
const ::uint32_t
    TableStruct_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::COVESA::IVDCT::TRUCK::ADAS::TCS::Tcs, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::COVESA::IVDCT::TRUCK::ADAS::TCS::Tcs, _impl_.isenabled_),
        PROTOBUF_FIELD_OFFSET(::COVESA::IVDCT::TRUCK::ADAS::TCS::Tcs, _impl_.iserror_),
        PROTOBUF_FIELD_OFFSET(::COVESA::IVDCT::TRUCK::ADAS::TCS::Tcs, _impl_.isengaged_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::COVESA::IVDCT::TRUCK::ADAS::TCS::Tcs)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::COVESA::IVDCT::TRUCK::ADAS::TCS::_Tcs_default_instance_._instance,
};
const char descriptor_table_protodef_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n%covesa/ivdct/truck/adas/tcs/tcs.proto\022"
    "\033COVESA.IVDCT.TRUCK.ADAS.TCS\"s\n\003Tcs\022\026\n\ti"
    "senabled\030\001 \001(\010H\000\210\001\001\022\024\n\007iserror\030\002 \001(\010H\001\210\001"
    "\001\022\026\n\tisengaged\030\003 \001(\010H\002\210\001\001B\014\n\n_isenabledB"
    "\n\n\010_iserrorB\014\n\n_isengagedb\006proto3"
};
static ::absl::once_flag descriptor_table_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto = {
    false,
    false,
    193,
    descriptor_table_protodef_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto,
    "covesa/ivdct/truck/adas/tcs/tcs.proto",
    &descriptor_table_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto::offsets,
    file_level_enum_descriptors_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto,
    file_level_service_descriptors_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto,
};
namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace ADAS {
namespace TCS {
// ===================================================================

class Tcs::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Tcs>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Tcs, _impl_._has_bits_);
};

Tcs::Tcs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Tcs_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
}
Tcs::Tcs(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Tcs& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Tcs_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Tcs::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Tcs::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, isenabled_),
           0,
           offsetof(Impl_, isengaged_) -
               offsetof(Impl_, isenabled_) +
               sizeof(Impl_::isengaged_));
}
Tcs::~Tcs() {
  // @@protoc_insertion_point(destructor:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
  SharedDtor(*this);
}
inline void Tcs::SharedDtor(MessageLite& self) {
  Tcs& this_ = static_cast<Tcs&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Tcs::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Tcs(arena);
}
constexpr auto Tcs::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Tcs),
                                            alignof(Tcs));
}
constexpr auto Tcs::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Tcs_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Tcs::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Tcs>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Tcs::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Tcs>(), &Tcs::ByteSizeLong,
              &Tcs::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Tcs, _impl_._cached_size_),
          false,
      },
      &Tcs::kDescriptorMethods,
      &descriptor_table_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Tcs_class_data_ =
        Tcs::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Tcs::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Tcs_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Tcs_class_data_.tc_table);
  return Tcs_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
Tcs::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Tcs, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Tcs_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::COVESA::IVDCT::TRUCK::ADAS::TCS::Tcs>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional bool isenabled = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Tcs, _impl_.isenabled_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(Tcs, _impl_.isenabled_)}},
    // optional bool iserror = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Tcs, _impl_.iserror_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Tcs, _impl_.iserror_)}},
    // optional bool isengaged = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(Tcs, _impl_.isengaged_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Tcs, _impl_.isengaged_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional bool isenabled = 1;
    {PROTOBUF_FIELD_OFFSET(Tcs, _impl_.isenabled_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool iserror = 2;
    {PROTOBUF_FIELD_OFFSET(Tcs, _impl_.iserror_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool isengaged = 3;
    {PROTOBUF_FIELD_OFFSET(Tcs, _impl_.isengaged_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Tcs::Clear() {
// @@protoc_insertion_point(message_clear_start:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.isenabled_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.isengaged_) -
      reinterpret_cast<char*>(&_impl_.isenabled_)) + sizeof(_impl_.isengaged_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Tcs::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Tcs& this_ = static_cast<const Tcs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Tcs::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Tcs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bool isenabled = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this_._internal_isenabled(), target);
  }

  // optional bool iserror = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this_._internal_iserror(), target);
  }

  // optional bool isengaged = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this_._internal_isengaged(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Tcs::ByteSizeLong(const MessageLite& base) {
  const Tcs& this_ = static_cast<const Tcs&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Tcs::ByteSizeLong() const {
  const Tcs& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x00000007u & cached_has_bits) * 2;
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Tcs::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Tcs*>(&to_msg);
  auto& from = static_cast<const Tcs&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.isenabled_ = from._impl_.isenabled_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.iserror_ = from._impl_.iserror_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.isengaged_ = from._impl_.isengaged_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Tcs::CopyFrom(const Tcs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Tcs::InternalSwap(Tcs* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Tcs, _impl_.isengaged_)
      + sizeof(Tcs::_impl_.isengaged_)
      - PROTOBUF_FIELD_OFFSET(Tcs, _impl_.isenabled_)>(
          reinterpret_cast<char*>(&_impl_.isenabled_),
          reinterpret_cast<char*>(&other->_impl_.isenabled_));
}

::google::protobuf::Metadata Tcs::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace TCS
}  // namespace ADAS
}  // namespace TRUCK
}  // namespace IVDCT
}  // namespace COVESA
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
