// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: covesa/ivdct/truck/adas/tcs/tcs.proto
// Protobuf C++ Version: 6.31.1

#ifndef covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto_2epb_2eh
#define covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto;
}  // extern "C"
namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace ADAS {
namespace TCS {
class Tcs;
struct TcsDefaultTypeInternal;
extern TcsDefaultTypeInternal _Tcs_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Tcs_class_data_;
}  // namespace TCS
}  // namespace ADAS
}  // namespace TRUCK
}  // namespace IVDCT
}  // namespace COVESA
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace COVESA {
namespace IVDCT {
namespace TRUCK {
namespace ADAS {
namespace TCS {

// ===================================================================


// -------------------------------------------------------------------

class Tcs final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs) */ {
 public:
  inline Tcs() : Tcs(nullptr) {}
  ~Tcs() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Tcs* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Tcs));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Tcs(::google::protobuf::internal::ConstantInitialized);

  inline Tcs(const Tcs& from) : Tcs(nullptr, from) {}
  inline Tcs(Tcs&& from) noexcept
      : Tcs(nullptr, ::std::move(from)) {}
  inline Tcs& operator=(const Tcs& from) {
    CopyFrom(from);
    return *this;
  }
  inline Tcs& operator=(Tcs&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Tcs& default_instance() {
    return *reinterpret_cast<const Tcs*>(
        &_Tcs_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Tcs& a, Tcs& b) { a.Swap(&b); }
  inline void Swap(Tcs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Tcs* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Tcs* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Tcs>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Tcs& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Tcs& from) { Tcs::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Tcs* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs"; }

 protected:
  explicit Tcs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Tcs(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Tcs& from);
  Tcs(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Tcs&& from) noexcept
      : Tcs(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIsenabledFieldNumber = 1,
    kIserrorFieldNumber = 2,
    kIsengagedFieldNumber = 3,
  };
  // optional bool isenabled = 1;
  bool has_isenabled() const;
  void clear_isenabled() ;
  bool isenabled() const;
  void set_isenabled(bool value);

  private:
  bool _internal_isenabled() const;
  void _internal_set_isenabled(bool value);

  public:
  // optional bool iserror = 2;
  bool has_iserror() const;
  void clear_iserror() ;
  bool iserror() const;
  void set_iserror(bool value);

  private:
  bool _internal_iserror() const;
  void _internal_set_iserror(bool value);

  public:
  // optional bool isengaged = 3;
  bool has_isengaged() const;
  void clear_isengaged() ;
  bool isengaged() const;
  void set_isengaged(bool value);

  private:
  bool _internal_isengaged() const;
  void _internal_set_isengaged(bool value);

  public:
  // @@protoc_insertion_point(class_scope:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Tcs& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool isenabled_;
    bool iserror_;
    bool isengaged_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Tcs_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Tcs

// optional bool isenabled = 1;
inline bool Tcs::has_isenabled() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Tcs::clear_isenabled() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isenabled_ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool Tcs::isenabled() const {
  // @@protoc_insertion_point(field_get:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs.isenabled)
  return _internal_isenabled();
}
inline void Tcs::set_isenabled(bool value) {
  _internal_set_isenabled(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs.isenabled)
}
inline bool Tcs::_internal_isenabled() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isenabled_;
}
inline void Tcs::_internal_set_isenabled(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isenabled_ = value;
}

// optional bool iserror = 2;
inline bool Tcs::has_iserror() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Tcs::clear_iserror() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iserror_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool Tcs::iserror() const {
  // @@protoc_insertion_point(field_get:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs.iserror)
  return _internal_iserror();
}
inline void Tcs::set_iserror(bool value) {
  _internal_set_iserror(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs.iserror)
}
inline bool Tcs::_internal_iserror() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iserror_;
}
inline void Tcs::_internal_set_iserror(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iserror_ = value;
}

// optional bool isengaged = 3;
inline bool Tcs::has_isengaged() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Tcs::clear_isengaged() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isengaged_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool Tcs::isengaged() const {
  // @@protoc_insertion_point(field_get:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs.isengaged)
  return _internal_isengaged();
}
inline void Tcs::set_isengaged(bool value) {
  _internal_set_isengaged(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:COVESA.IVDCT.TRUCK.ADAS.TCS.Tcs.isengaged)
}
inline bool Tcs::_internal_isengaged() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isengaged_;
}
inline void Tcs::_internal_set_isengaged(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isengaged_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace TCS
}  // namespace ADAS
}  // namespace TRUCK
}  // namespace IVDCT
}  // namespace COVESA


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // covesa_2fivdct_2ftruck_2fadas_2ftcs_2ftcs_2eproto_2epb_2eh
