// Code generated by protoc-gen-validate
// source: vh_hf/vh_hf.proto
// DO NOT EDIT!!!

#include "vh_hf/vh_hf.pb.validate.h"

#include <google/protobuf/message.h>
#include <google/protobuf/util/time_util.h>
#include "re2/re2.h"

namespace pgv {

namespace protobuf = google::protobuf;
namespace protobuf_wkt = google::protobuf;

namespace validate {
using std::string;

// define the regex for a UUID once up-front
const re2::RE2 _uuidPattern("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$");

pgv::Validator<::VH_HF::VH_hf> validator___VH_HF__VH_hf(static_cast<bool(*)(const ::VH_HF::VH_hf&, pgv::ValidationMsg*)>(::VH_HF::Validate));


} // namespace validate
} // namespace pgv


namespace VH_HF {


// Validate checks the field values on ::VH_HF::VH_hf with the rules defined in
// the proto definition for this message. If any rules are violated, the
// return value is false and an error message is written to the input string argument.

	

	

	

	

        

	

	

	



bool Validate(const ::VH_HF::VH_hf& m, pgv::ValidationMsg* err) {
	(void)m;
	(void)err;
			if (m.has_gnss()) {
				
	
	
	

	
	{
		pgv::ValidationMsg inner_err;
		if (m.has_gnss() && !pgv::BaseValidator::AbstractCheckMessage(m.gnss(), &inner_err)) {
			{
std::ostringstream msg("invalid ");
msg << "VH_hfValidationError" << "." << "Gnss";
msg << ": " << "embedded message failed validation";
msg << " | caused by " << inner_err;
*err = msg.str();
return false;
}
		}
	}
	

			}
		
		
	return true;
}


} // namespace

