#include <V2XHO_Node_Solicitation_Include.h>

#define SOLICITATION_PACKET_LEGNTH 256

#define SOLICITATION_ADDRESS "224.0.0.11"
#define SOLICITATION_PORT 434
#define SOLICITATION_ROUTER_ADDRESS ""
#define SOLICITATION_NUM_ADDRS 0
#define SOLICITATION_PERFERENCE_LEVER 0
#define MAX_SOLICITATION_DELAY 1
#define MAX_SOLICITATIONS 3
#define SOLICITATION_INTERVAL 3
#define SOLICITATION_ROUTER_DISCOVERY true

