// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vh_lf/comm/status/status.proto
// Protobuf C++ Version: 6.31.1

#include "vh_lf/comm/status/status.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace VH_LF {
namespace COMM {
namespace STATUS {

inline constexpr Status::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::VH_LF::COMM::STATUS::Status_Type >(0)},
        quality_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Status::Status(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Status_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusDefaultTypeInternal() {}
  union {
    Status _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusDefaultTypeInternal _Status_default_instance_;
}  // namespace STATUS
}  // namespace COMM
}  // namespace VH_LF
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto = nullptr;
const ::uint32_t
    TableStruct_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::VH_LF::COMM::STATUS::Status, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::VH_LF::COMM::STATUS::Status, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::VH_LF::COMM::STATUS::Status, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::VH_LF::COMM::STATUS::Status, _impl_.quality_),
        0,
        1,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::VH_LF::COMM::STATUS::Status)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::VH_LF::COMM::STATUS::_Status_default_instance_._instance,
};
const char descriptor_table_protodef_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\036vh_lf/comm/status/status.proto\022\021VH_LF."
    "COMM.STATUS\032\027validate/validate.proto\"\271\002\n"
    "\006Status\022\032\n\002id\030\001 \001(\tB\t\372B\006r\004\020\001\030 H\000\210\001\001\022;\n\004t"
    "ype\030\002 \001(\0162\036.VH_LF.COMM.STATUS.Status.Typ"
    "eB\010\372B\005\202\001\002\020\001H\001\210\001\001\022\024\n\007quality\030\003 \001(\005H\002\210\001\001\"\243"
    "\001\n\004Type\022\031\n\025COMMON_STATUS_UNKNOWN\020\000\022\032\n\026CO"
    "MMON_STATUS_DSRC_V2X\020\001\022\031\n\025COMMON_STATUS_"
    "LTE_V2X\020\002\022\030\n\024COMMON_STATUS_NR_V2X\020\003\022\025\n\021C"
    "OMMON_STATUS_LTE\020\004\022\030\n\024COMMON_STATUS_FIVE"
    "_G\020\005B\005\n\003_idB\007\n\005_typeB\n\n\010_qualityb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto_deps[1] = {
        &::descriptor_table_validate_2fvalidate_2eproto,
};
static ::absl::once_flag descriptor_table_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto = {
    false,
    false,
    400,
    descriptor_table_protodef_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto,
    "vh_lf/comm/status/status.proto",
    &descriptor_table_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto_once,
    descriptor_table_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto::offsets,
    file_level_enum_descriptors_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto,
    file_level_service_descriptors_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto,
};
namespace VH_LF {
namespace COMM {
namespace STATUS {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Status_Type_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto);
  return file_level_enum_descriptors_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Status_Type_internal_data_[] = {
    393216u, 0u, };
// ===================================================================

class Status::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Status>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Status, _impl_._has_bits_);
};

Status::Status(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Status_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:VH_LF.COMM.STATUS.Status)
}
PROTOBUF_NDEBUG_INLINE Status::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::VH_LF::COMM::STATUS::Status& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_) {}

Status::Status(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Status& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Status_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Status* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, quality_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::quality_));

  // @@protoc_insertion_point(copy_constructor:VH_LF.COMM.STATUS.Status)
}
PROTOBUF_NDEBUG_INLINE Status::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena) {}

inline void Status::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, quality_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::quality_));
}
Status::~Status() {
  // @@protoc_insertion_point(destructor:VH_LF.COMM.STATUS.Status)
  SharedDtor(*this);
}
inline void Status::SharedDtor(MessageLite& self) {
  Status& this_ = static_cast<Status&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Status::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Status(arena);
}
constexpr auto Status::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Status),
                                            alignof(Status));
}
constexpr auto Status::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Status_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Status::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Status>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Status::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Status>(), &Status::ByteSizeLong,
              &Status::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Status, _impl_._cached_size_),
          false,
      },
      &Status::kDescriptorMethods,
      &descriptor_table_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Status_class_data_ =
        Status::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Status::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Status_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Status_class_data_.tc_table);
  return Status_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 35, 2>
Status::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Status, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Status_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::VH_LF::COMM::STATUS::Status>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string id = 1 [(.validate.rules) = {
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Status, _impl_.id_)}},
    // optional .VH_LF.COMM.STATUS.Status.Type type = 2 [(.validate.rules) = {
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Status, _impl_.type_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(Status, _impl_.type_)}},
    // optional int32 quality = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Status, _impl_.quality_), 2>(),
     {24, 2, 0, PROTOBUF_FIELD_OFFSET(Status, _impl_.quality_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string id = 1 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(Status, _impl_.id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // optional .VH_LF.COMM.STATUS.Status.Type type = 2 [(.validate.rules) = {
    {PROTOBUF_FIELD_OFFSET(Status, _impl_.type_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // optional int32 quality = 3;
    {PROTOBUF_FIELD_OFFSET(Status, _impl_.quality_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\30\2\0\0\0\0\0\0"
    "VH_LF.COMM.STATUS.Status"
    "id"
  }},
};
PROTOBUF_NOINLINE void Status::Clear() {
// @@protoc_insertion_point(message_clear_start:VH_LF.COMM.STATUS.Status)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.id_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x00000006u) != 0) {
    ::memset(&_impl_.type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.quality_) -
        reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.quality_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Status::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Status& this_ = static_cast<const Status&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Status::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Status& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:VH_LF.COMM.STATUS.Status)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string id = 1 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "VH_LF.COMM.STATUS.Status.id");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional .VH_LF.COMM.STATUS.Status.Type type = 2 [(.validate.rules) = {
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this_._internal_type(), target);
  }

  // optional int32 quality = 3;
  if ((cached_has_bits & 0x00000004u) != 0) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_quality(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VH_LF.COMM.STATUS.Status)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Status::ByteSizeLong(const MessageLite& base) {
  const Status& this_ = static_cast<const Status&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Status::ByteSizeLong() const {
  const Status& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:VH_LF.COMM.STATUS.Status)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // optional string id = 1 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_id());
    }
    // optional .VH_LF.COMM.STATUS.Status.Type type = 2 [(.validate.rules) = {
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
    }
    // optional int32 quality = 3;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_quality());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Status::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Status*>(&to_msg);
  auto& from = static_cast<const Status&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:VH_LF.COMM.STATUS.Status)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_id(from._internal_id());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.type_ = from._impl_.type_;
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_impl_.quality_ = from._impl_.quality_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Status::CopyFrom(const Status& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VH_LF.COMM.STATUS.Status)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Status::InternalSwap(Status* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Status, _impl_.quality_)
      + sizeof(Status::_impl_.quality_)
      - PROTOBUF_FIELD_OFFSET(Status, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata Status::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace STATUS
}  // namespace COMM
}  // namespace VH_LF
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_vh_5flf_2fcomm_2fstatus_2fstatus_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
