// Code generated by protoc-gen-validate
// source: ads_lf/sensor/orientation/orientation.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "ads_lf/sensor/orientation/orientation.pb.h"


namespace ADS_LF {
namespace SENSOR {
namespace ORIENTATION {

using std::string;


extern bool Validate(const ::ADS_LF::SENSOR::ORIENTATION::Orientation& m, pgv::ValidationMsg* err);


} // namespace
} // namespace
} // namespace


#define X_ADS_LF_SENSOR_ORIENTATION_ORIENTATION(X) \
X(::ADS_LF::SENSOR::ORIENTATION::Orientation) \

