// Code generated by protoc-gen-validate
// source: dtg/vehicle/vehicle.proto
// DO NOT EDIT!!!

#pragma once

#include <algorithm>
#include <string>
#include <sstream>
#include <unordered_set>
#include <vector>

#include "validate/validate.h"
#include "dtg/vehicle/vehicle.pb.h"


namespace DTG {
namespace VEHICLE {

using std::string;


extern bool Validate(const ::DTG::VEHICLE::Vehicle& m, pgv::ValidationMsg* err);


} // namespace
} // namespace


#define X_DTG_VEHICLE_VEHICLE(X) \
X(::DTG::VEHICLE::Vehicle) \

