// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ads_hf/lane/inclination/inclination.proto
// Protobuf C++ Version: 6.31.1

#ifndef ads_5fhf_2flane_2finclination_2finclination_2eproto_2epb_2eh
#define ads_5fhf_2flane_2finclination_2finclination_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "validate/validate.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ads_5fhf_2flane_2finclination_2finclination_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ads_5fhf_2flane_2finclination_2finclination_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ads_5fhf_2flane_2finclination_2finclination_2eproto;
}  // extern "C"
namespace ADS_HF {
namespace LANE {
namespace INCLINATION {
class Inclination;
struct InclinationDefaultTypeInternal;
extern InclinationDefaultTypeInternal _Inclination_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Inclination_class_data_;
}  // namespace INCLINATION
}  // namespace LANE
}  // namespace ADS_HF
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace ADS_HF {
namespace LANE {
namespace INCLINATION {

// ===================================================================


// -------------------------------------------------------------------

class Inclination final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ADS_HF.LANE.INCLINATION.Inclination) */ {
 public:
  inline Inclination() : Inclination(nullptr) {}
  ~Inclination() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Inclination* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Inclination));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Inclination(::google::protobuf::internal::ConstantInitialized);

  inline Inclination(const Inclination& from) : Inclination(nullptr, from) {}
  inline Inclination(Inclination&& from) noexcept
      : Inclination(nullptr, ::std::move(from)) {}
  inline Inclination& operator=(const Inclination& from) {
    CopyFrom(from);
    return *this;
  }
  inline Inclination& operator=(Inclination&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Inclination& default_instance() {
    return *reinterpret_cast<const Inclination*>(
        &_Inclination_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Inclination& a, Inclination& b) { a.Swap(&b); }
  inline void Swap(Inclination* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Inclination* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Inclination* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Inclination>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Inclination& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Inclination& from) { Inclination::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Inclination* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ADS_HF.LANE.INCLINATION.Inclination"; }

 protected:
  explicit Inclination(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Inclination(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Inclination& from);
  Inclination(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Inclination&& from) noexcept
      : Inclination(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLateralFieldNumber = 1,
    kLongitudinalFieldNumber = 2,
  };
  // optional int32 lateral = 1 [(.validate.rules) = {
  bool has_lateral() const;
  void clear_lateral() ;
  ::int32_t lateral() const;
  void set_lateral(::int32_t value);

  private:
  ::int32_t _internal_lateral() const;
  void _internal_set_lateral(::int32_t value);

  public:
  // optional int32 longitudinal = 2 [(.validate.rules) = {
  bool has_longitudinal() const;
  void clear_longitudinal() ;
  ::int32_t longitudinal() const;
  void set_longitudinal(::int32_t value);

  private:
  ::int32_t _internal_longitudinal() const;
  void _internal_set_longitudinal(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:ADS_HF.LANE.INCLINATION.Inclination)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Inclination& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t lateral_;
    ::int32_t longitudinal_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ads_5fhf_2flane_2finclination_2finclination_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Inclination_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Inclination

// optional int32 lateral = 1 [(.validate.rules) = {
inline bool Inclination::has_lateral() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Inclination::clear_lateral() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lateral_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t Inclination::lateral() const {
  // @@protoc_insertion_point(field_get:ADS_HF.LANE.INCLINATION.Inclination.lateral)
  return _internal_lateral();
}
inline void Inclination::set_lateral(::int32_t value) {
  _internal_set_lateral(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:ADS_HF.LANE.INCLINATION.Inclination.lateral)
}
inline ::int32_t Inclination::_internal_lateral() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.lateral_;
}
inline void Inclination::_internal_set_lateral(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lateral_ = value;
}

// optional int32 longitudinal = 2 [(.validate.rules) = {
inline bool Inclination::has_longitudinal() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Inclination::clear_longitudinal() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitudinal_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t Inclination::longitudinal() const {
  // @@protoc_insertion_point(field_get:ADS_HF.LANE.INCLINATION.Inclination.longitudinal)
  return _internal_longitudinal();
}
inline void Inclination::set_longitudinal(::int32_t value) {
  _internal_set_longitudinal(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:ADS_HF.LANE.INCLINATION.Inclination.longitudinal)
}
inline ::int32_t Inclination::_internal_longitudinal() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.longitudinal_;
}
inline void Inclination::_internal_set_longitudinal(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.longitudinal_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace INCLINATION
}  // namespace LANE
}  // namespace ADS_HF


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ads_5fhf_2flane_2finclination_2finclination_2eproto_2epb_2eh
